caseI = {
	0:{//贸易电商
		navI:[
			{
				pic:'/tpl/home/good/common/images/15/logo.jpg',
				name:'浙江百诚集团'
			},
			{
				pic:'/tpl/home/good/common/images/1/logo.jpg',
				name:'BORLEIGH铂丽'
			},
			{
				pic:'/tpl/home/good/common/images/18/logo.jpg',
				name:'广奇游乐设备'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/15/1.jpg',
				pic2:'/tpl/home/good/common/images/15/2.jpg',
				code:'/tpl/home/good/common/images/15/code.jpg',
				text:'浙江百诚集团股份有限公司位于杭州市上城区惠民路（原浙江省商业厅大院内），是一家以电器、珠宝、汽车销售为主的大型商贸企业，公司代理品牌涉及家电、珠宝、汽车、化工原料、工业电气等多个行业的60多个品牌，其中近三分之一是全球500强企业的产品。'
			},
			{
				pic1:'/tpl/home/good/common/images/1/1.jpg',
				pic2:'/tpl/home/good/common/images/1/2.jpg',
				code:'/tpl/home/good/common/images/1/code.jpg',
				text:'东莞市铂丽鞋业有限公司是香港诗珺集团于2007年投资的全资子公司, 是一家集开发、生产、销售于一体的综合性公司，强大的开发、生产队伍, 以保证铂丽新款上市新和快之品牌特点。'
			},
			{
				pic1:'/tpl/home/good/common/images/18/1.jpg',
				pic2:'/tpl/home/good/common/images/18/2.jpg',
				code:'/tpl/home/good/common/images/18/code.jpg',
				text:'       仙居县广奇游乐设备厂是一家专业生产充气电瓶车，机器人黄包车，卡通黄包车，充气城堡，充气玩具，淘气堡，碰碰车，摇摆机、跷跷板、叮咚锤，轨道火车、电动玩具，机械玩具，玻璃钢制品等游乐玩具的私营企业。 '
			}
		]
	},
	1:{//杂志刊物
		navI:[
			{
				pic:'/tpl/home/good/common/images/2/logo.jpg',
				name:'妈妈圈微报'
			},
			{
				pic:'/tpl/home/good/common/images/21/logo.jpg',
				name:'精品消费报'
			},
			{
				pic:'/tpl/home/good/common/images/22/logo.jpg',
				name:'精品试妆达人'
			},
			{
				pic:'/tpl/home/good/common/images/41/logo.jpg',
				name:'时尚育儿杂志'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/2/1.jpg',
				pic2:'/tpl/home/good/common/images/2/2.jpg',
				code:'/tpl/home/good/common/images/2/code.jpg',
				text:'20万妈妈们每天必看的育儿应用，让怀孕、生产和育儿知识像微博一样可以轻松阅读，更有《时尚育儿杂志》的权威专家每天坐镇，免费提供育儿咨询。'
			},
			{
				pic1:'/tpl/home/good/common/images/21/1.jpg',
				pic2:'/tpl/home/good/common/images/21/2.jpg',
				code:'/tpl/home/good/common/images/21/code.jpg',
				text:'作为云南日报报业集团下的新刊物，《精品消费报》是与北京《精品购物指南》合力打造的消费周报。精品消费报价格低，但是在这里，读者可以看到最前沿、最时尚、最新的资讯，吃喝玩乐样样都有。活动由云南日报报业集团下的云南报刊发行有限责任公司推出，希望借作为昆滇市场唯一一份日发行超过30万份的《春城晚报》，让《精品消费报》和读者更加亲近，让读者能享受到一份最具综合内容的都市类报纸，加一份实用资讯大全的时尚刊物。'
			},
			{
				pic1:'/tpl/home/good/common/images/22/1.jpg',
				pic2:'/tpl/home/good/common/images/22/2.jpg',
				code:'/tpl/home/good/common/images/22/code.jpg',
				text:'  惊喜大礼拿不完，专家明星随时约，更有机会荣登《精品购物指南》版面！一大波福利正向你靠近哦！快加入我们吧！ 【精品消费报】beauty官方微信'
			},
			{
				pic1:'/tpl/home/good/common/images/41/1.jpg',
				pic2:'/tpl/home/good/common/images/41/2.jpg',
				code:'/tpl/home/good/common/images/41/code.jpg',
				text:'《时尚育儿》获得了权威的医疗、教育机构和专家学者的支持和指导，向读者提供全面科学的孕产、医护、营养、早教、消费等方面的知识与建议。以“面对面交流、手把手指导”为编辑特色，提供0~3岁宝宝的家庭必需的育儿知识，是国内更科学、更互动、更时尚的育儿杂志。'
			}
		]
	},
	2:{//互联网
		navI:[
			{
				pic:'/tpl/home/good/common/images/3/logo.jpg',
				name:'小麦工场'
			},
			{
				pic:'/tpl/home/good/common/images/6/logo.jpg',
				name:'无锡智达'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/3/1.jpg',
				pic2:'/tpl/home/good/common/images/3/2.jpg',
				code:'/tpl/home/good/common/images/3/code.jpg',
				text:'小麦工场从2010年开始一直为品牌企业提供电商代运营,微博托管及代运营,口碑营销,微信代运营等服务。集聚了多名国内著名IT互联网企业的行业精英，是一支富有激情，经验丰富的团队。 我们郑重承诺：以帮助企业开展获得商业效果为唯一宗旨全心全力为每一个客户创造应有的价值。'
			},
			{
				pic1:'/tpl/home/good/common/images/6/1.jpg',
				pic2:'/tpl/home/good/common/images/6/2.jpg',
				code:'/tpl/home/good/common/images/6/code.jpg',
				text:'无锡市智达网络科技有限公司，坐落于江南水乡，景色秀丽，环境优美！自2006年6月8日成立至今，从域名注册，网站建设，不断的壮大我们的客户群，应越来越多企业和个人站长的需求，服务器的托管和租用也成为公司服务的项目之一，公司也由网站建设向idc业务扩展，以低廉的价格，优质的质量，满意的服务，深受广大用户的青睐。'
			}
		]
	},
	3:{//行业协会
		navI:[
			{
				pic:'/tpl/home/good/common/images/4/logo.jpg',
				name:'浙江家电'
			},
			{
				pic:'/tpl/home/good/common/images/19/logo.jpg',
				name:'曲靖商会'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/4/1.jpg',
				pic2:'/tpl/home/good/common/images/4/2.jpg',
				code:'/tpl/home/good/common/images/4/code.jpg',
				text:'浙江商贸业联合会家电商业专业委员会成立于2011年11月23日，作为浙江省家电商贸流通领域首个行业自愿性自律组织。浙江省商贸业联合会家电商业专业委员会将积极响应国家扩大内需与转型升级的政策号召，致力于为政府、企业和社会打造高效沟通互动的平台，准确把握新政策的趋势和走向，加强各企业在发展过程中的交流合作，促进家电产业的振兴和市场的繁荣，助力浙江经济的又一次腾飞。'
			},
			{
				pic1:'/tpl/home/good/common/images/19/1.jpg',
				pic2:'/tpl/home/good/common/images/19/2.jpg',
				code:'/tpl/home/good/common/images/19/code.jpg',
				text:'昆明市曲靖商会，是由云南曲靖籍在昆经商的企业家及社会各界人士自愿发起成立的公共组织，以“兴商报国，普济众生” 为使命，“正德厚生，互通共荣”为价值观，将分散的曲商力量凝聚起来，做中国最有价值的公共组织。'
			}
		]
	},
	4:{//食品加工
		navI:[
			{
				pic:'/tpl/home/good/common/images/5/logo.jpg',
				name:'牧优有机羊奶'
			},
			{
				pic:'/tpl/home/good/common/images/26/logo.jpg',
				name:'大成农业'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/5/1.jpg',
				pic2:'/tpl/home/good/common/images/5/2.jpg',
				code:'/tpl/home/good/common/images/5/code.jpg',
				text:'“牧优”系列自2012年上市后，目前已在上海、浙江、江苏、山东、广东、福建、天津等全国26个省及直辖市母婴专业店销售，并通过其卓越的品质、贴心的售后服务快速的取得了消费者及业内的认可。我们专为每一位消费者开设24小时全天候贴心客服服务，任何与宝宝有关的事宜都欢迎致电400-606-5759全国免费营养热线，我们竭诚为您服务！'
			},
			{
				pic1:'/tpl/home/good/common/images/26/1.jpg',
				pic2:'/tpl/home/good/common/images/26/2.jpg',
				code:'/tpl/home/good/common/images/26/code.jpg',
				text:'昭通市大成农业开发有限责任公司是2009年经鲁甸县人民政府招商引资于2009年8月在鲁甸县工商行政管理局注册成立的农业开发公司，注册资金500万元，公司现有员工45人，花椒加工机械设施有花椒清选机、比重精选机、烘干机、电脑包装机、花椒挥发油提取设备、花椒麻味素提取设、花椒油浸泡设施和检验设施一套。'
			}
		]
	},
	5:{//咖啡
		navI:[
			{
				pic:'/tpl/home/good/common/images/29/logo.jpg',
				name:'小粒香'
			},
			{
				pic:'/tpl/home/good/common/images/7/logo.jpg',
				name:'南来盛咖啡'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/29/1.jpg',
				pic2:'/tpl/home/good/common/images/29/2.jpg',
				code:'/tpl/home/good/common/images/29/code.jpg',
				text:'云南小粒香咖啡公司是以小粒种咖啡种植、研发、生产、销售、培训于一体的多元化公司。我们始终坚持“共同发展、合作共赢”的经营理念，全心打造云南小粒咖啡一站式服务平台，为您提供高品质的服务。'
			},
			{
				pic1:'/tpl/home/good/common/images/7/1.jpg',
				pic2:'/tpl/home/good/common/images/7/2.jpg',
				code:'/tpl/home/good/common/images/7/code.jpg',
				text:'2013年，金碧路金马碧鸡坊商业步行街区JB3-2-1商铺三楼，“南来盛”得以恢复重现。再一次让法式咖啡香飘春城。到春城走进南来盛，是穿越食品“时间隧道”的探寻，是品位老树新花的享受！'
			}
		]
	},
	6:{//餐饮
		navI:[
			{
				pic:'/tpl/home/good/common/images/8/logo.jpg',
				name:'湖南味视'
			},
			{
				pic:'/tpl/home/good/common/images/10/logo.jpg',
				name:'醉美江西'
			},
			{
				pic:'/tpl/home/good/common/images/12/logo.jpg',
				name:'金海港'
			},
			{
				pic:'/tpl/home/good/common/images/33/logo.jpg',
				name:'鑫鱼园'
			},
			{
				pic:'/tpl/home/good/common/images/36/logo.jpg',
				name:'和顺居'
			},
			{
				pic:'/tpl/home/good/common/images/31/logo.jpg',
				name:'外婆味道'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/8/1.jpg',
				pic2:'/tpl/home/good/common/images/8/2.jpg',
				code:'/tpl/home/good/common/images/8/code.jpg',
				text:'以湖南娱乐文化为背景，致力最正宗的湖南菜。我们将传统的湘菜文化与时尚的湖南娱乐文化相结合，创造出独特的味道好，服务好，环境好。欢迎您光临！'
			},
			{
				pic1:'/tpl/home/good/common/images/10/1.jpg',
				pic2:'/tpl/home/good/common/images/10/2.jpg',
				code:'/tpl/home/good/common/images/10/code.jpg',
				text:'醉美江西酒楼以经营餐饮为主，采用全方位、高标准、优质量服务方式，可承办大型高中宴会、喜庆家宴、业务洽谈、旅游订餐等。注重清、香、鲜、嫩、脆，拿手名菜，为您提供舒适安全的服务。欢迎您光临！'
			},
			{
				pic1:'/tpl/home/good/common/images/12/1.jpg',
				pic2:'/tpl/home/good/common/images/12/2.jpg',
				code:'/tpl/home/good/common/images/12/code.jpg',
				text:'金海港海鲜大酒楼，以“新派粤菜、精品海鲜”为主题，致力打造最正宗新派粤菜；我们将传统的粤菜文化与时尚新颖的新派粤菜相结合，创造独特的味道好、服务好、环境好。 欢迎您的光临！'
			},
			{
				pic1:'/tpl/home/good/common/images/33/1.jpg',
				pic2:'/tpl/home/good/common/images/33/2.jpg',
				code:'/tpl/home/good/common/images/33/code.jpg',
				text:'曲靖鑫鱼园时尚鲜鱼餐厅是曲靖市拥有百强餐饮企业称号的一家本土知名企业，自1993年创办第一家以专营鲜鱼为主的餐厅以来，董事长袁利贵本着以质量保障为基础，服务满意为保证的经营理念，着力打造曲靖鑫鱼源品牌餐饮文化建设。'
			},
			{
				pic1:'/tpl/home/good/common/images/36/1.jpg',
				pic2:'/tpl/home/good/common/images/36/2.jpg',
				code:'/tpl/home/good/common/images/36/code.jpg',
				text:'红河和顺美食文化传播有限责任公司---于2006年3月30日注册成立，企业本着“从善自然美食、健康、美味   ---和顺居”为使命，以“自然、绿色环保的食品资源战略整合方案提供商”为战略定位，让在和顺奋斗过的人，在不远的将来可以用懒惰、不劳动、不动脑筋获得生活保障！'
			},
			{
				pic1:'/tpl/home/good/common/images/31/1.jpg',
				pic2:'/tpl/home/good/common/images/31/2.jpg',
				code:'/tpl/home/good/common/images/31/code.jpg',
				text:'外婆味道餐饮集团成立于2000年9月，目前旗下有“外婆味道、热火朝天、兴龙园、田园庄、彝山乐”五大餐饮品牌。外婆味道继承外婆做菜“少油、少盐、少调料”的原则，以“回归本味、味美价廉”为宗旨，打造云南性价比最高的大型平价餐饮企业。'
			}
			
		]
	},
	7:{//广告媒体
		navI:[
			{
				pic:'/tpl/home/good/common/images/9/logo.jpg',
				name:'企都广告'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/9/1.jpg',
				pic2:'/tpl/home/good/common/images/9/2.jpg',
				code:'/tpl/home/good/common/images/9/code.jpg',
				text:'昆明企都广告成立于二零零四年，作为昆明公交集团下属的一级代理商，我公司主要代理昆明公交集团所有线路小巴车车体广告，远郊车车体广告，部分12米车、10米车、8米车车体广告，所有公交大巴的车内平面媒体，呈贡新区站台广告。'
			}
		]
	},
	8:{//家居建材
		navI:[
			{
				pic:'/tpl/home/good/common/images/11/logo.jpg',
				name:'凡尔赛'
			},
			{
				pic:'/tpl/home/good/common/images/23/logo.jpg',
				name:'科达装饰'
			},
			{
				pic:'/tpl/home/good/common/images/39/logo.jpg',
				name:'华庭墙纸'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/11/1.jpg',
				pic2:'/tpl/home/good/common/images/11/2.jpg',
				code:'/tpl/home/good/common/images/11/code.jpg',
				text:'凡尔赛建材馆是由宣威傲龙投资建设，主要用于建材家居销售。经营品类涵盖陶瓷、卫浴、洁具、灯具、电器、木地板、家居、窗帘、橱柜、集成吊顶、窗帘、壁纸等，真正打造了方便消费者一站式采购的大型建材家居服务中心。'
			},
			{
				pic1:'/tpl/home/good/common/images/23/1.jpg',
				pic2:'/tpl/home/good/common/images/23/2.jpg',
				code:'/tpl/home/good/common/images/23/code.jpg',
				text:'云南科达科达建设工程集团有限公司（以下简称科达集团)在公司创始人王永红先生的带领和全体科达员工的不懈努力下，经过二十载风雨同舟的艰辛努力,广大员工经过千锤百炼的磨砺、历尽了大浪淘沙的洗礼。科达集团的一叶美丽方舟已经驶至穿金路769号,并拥有13500平方米的现代化办公楼和展览大厅。科达集团已经升格为云南建筑装饰行业的一面旗帜——云南科达建设工程集团。'
			},
			{
				pic1:'/tpl/home/good/common/images/39/1.jpg',
				pic2:'/tpl/home/good/common/images/39/2.jpg',
				code:'/tpl/home/good/common/images/39/code.jpg',
				text:'独山明星布艺华庭墙纸，专营中高端布艺窗帘，墙纸，墙画，墙布。。。'
			}
		]
	},
	9:{//旅游
		navI:[
			{
				pic:'/tpl/home/good/common/images/13/logo.jpg',
				name:'今日旅游'
			},
			{	pic:'/tpl/home/good/common/images/16/logo.jpg',
				name:'世博国际旅行社'
			},
			{	pic:'/tpl/home/good/common/images/45/logo.jpg',
				name:'桂林中水国际酒店'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/13/1.jpg',
				pic2:'/tpl/home/good/common/images/13/2.jpg',
				code:'/tpl/home/good/common/images/13/code.jpg',
				text:'《云南今日旅游》是一个覆盖云南全省所有旅行社、省外部分云南专线客户的专业旅游同行内部交流媒体，致力于为旅游同行提供快捷、高效、真实的沟通交流服务。'
			},
			{
				pic1:'/tpl/home/good/common/images/16/1.jpg',
				pic2:'/tpl/home/good/common/images/16/2.jpg',
				code:'/tpl/home/good/common/images/16/code.jpg',
				text:'云南世博国际旅行社有限公司分属于云南世博旅游控股集团有限公司。公司主要经营项目包含了出境旅游，国内旅游，同时也是省内旅游的昆明、大理、丽江、中甸、泸沽湖、版纳、腾冲、瑞丽等的专线批发商。'
			},
			{
				pic1:'/tpl/home/good/common/images/45/1.jpg',
				pic2:'/tpl/home/good/common/images/45/2.jpg',
				code:'/tpl/home/good/common/images/45/code.jpg',
				text:'中水国际酒店位于桂林市崇信路50号（南溪山旁原海洋馆），紧临南溪山公园，毗邻漓江，风景如画，闹中取静，距两江国际机场30分钟，距火车站仅1公里，距汽车站2公里，交通十分便捷。秉承“顾客至上，宾至如归”的经营理念，诚挚地欢迎您的光临，中水国际酒店是您休闲、旅游、度假和商务的最佳选择！'
			}
		]
	},
	10:{//教育培训
		navI:[
			{
				pic:'/tpl/home/good/common/images/14/logo.jpg',
				name:'约亚企业'
			},
			{
				pic:'/tpl/home/good/common/images/30/logo.jpg',
				name:'财富论道'
			},
			{
				pic:'/tpl/home/good/common/images/46/logo.jpg',
				name:'天元教育濮阳站'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/14/1.jpg',
				pic2:'/tpl/home/good/common/images/14/2.jpg',
				code:'/tpl/home/good/common/images/14/code.jpg',
				text:'约亚企业是云南本土较早的一家企业培训机构，公司本着：‘天下为公 ，企业为众’的原则，为云南众多知名企业打造出大批的销售、高级管理人才。'
			},
			{
				pic1:'/tpl/home/good/common/images/30/1.jpg',
				pic2:'/tpl/home/good/common/images/30/2.jpg',
				code:'/tpl/home/good/common/images/30/code.jpg',
				text:'道可道，非常道，财富亦有道。我们将使用杂志传媒和移动互联网媒介为你开设财富讲坛、财富论坛、财富商学院、品牌企业会、MBA视野等栏目，欢迎你投稿或出资宣传自己及事业，成功之道在于宣传、宣传再宣传。'
			},
			{
				pic1:'/tpl/home/good/common/images/46/1.jpg',
				pic2:'/tpl/home/good/common/images/46/2.jpg',
				code:'/tpl/home/good/common/images/46/code.jpg',
				text:'天元教育是专门针对公务员考试进行研究、培训的品牌机构，办学多年，业绩突出，凭借“教学质量高于一切” 的宗旨，在业界树立了极佳的口碑，这一切都基于我们的教研室内囊括了省内最具权威的公考培训专家，多年来致力于公务员录用考试命题研究和考试培训工作。'
			}
		]
	},
	11:{//政府
		navI:[
			{
				pic:'/tpl/home/good/common/images/17/logo.jpg',
				name:'台州椒江住房公积金'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/17/1.jpg',
				pic2:'/tpl/home/good/common/images/17/2.jpg',
				code:'/tpl/home/good/common/images/17/code.jpg',
				text:'       台州市住房公积金管理中心椒江分中心是台州市住房公积金管理中心派出机构，参照公务员法管理科级事业单位。根据台州市住房公积金管理中心的授权，负责辖区内住房公积金的归集、提取、贷款及报表编制等具体管理工作。 '
			}
		]
	},
	12:{//生物科技
		navI:[
			{
				pic:'/tpl/home/good/common/images/43/logo.jpg',
				name:'深圳恒源节能'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/43/1.jpg',
				pic2:'/tpl/home/good/common/images/43/2.jpg',
				code:'/tpl/home/good/common/images/43/code.jpg',
				text:'深圳市恒源节能技术有限公司是专业从事变频控制系统的优质服务商，并为客户提供周到的变频器售前、售中、售后服务。公司主营变频器品牌：蓝海华腾、正弦、安邦信节能项目改造与变频器维修业务'
			}
		]
	},
	13:{//房地产
		navI:[
			{
				pic:'/tpl/home/good/common/images/20/logo.jpg',
				name:'天马房地产'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/20/1.jpg',
				pic2:'/tpl/home/good/common/images/20/2.jpg',
				code:'/tpl/home/good/common/images/20/code.jpg',
				text:'       天马房地产开发经营有限公司成立于2001年8月，是一个具备二级开发资质的房地产企业。公司下辖建筑安装、物业服务、电气安装、水力发电站等企业，形成了“以房地产业为主、相关产业有限多元发展”的产业布局。'
			}
		]
	},
	14:{//娱乐
		navI:[
			{
				pic:'/tpl/home/good/common/images/27/logo.jpg',
				name:'天丽歌剧院'
			},
			{
				pic:'/tpl/home/good/common/images/34/logo.jpg',
				name:'酷琪KTV'
			},
			{
				pic:'/tpl/home/good/common/images/35/logo.jpg',
				name:'菲梵瑜伽肚皮舞'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/27/1.jpg',
				pic2:'/tpl/home/good/common/images/27/2.jpg',
				code:'/tpl/home/good/common/images/27/code.jpg',
				text:'曲靖时尚圈-曲靖天丽歌剧院耗资千万打造的最具实力的娱乐品牌，坚持把创造开心，传播开心的高雅节目形式及经营管理理念带到您身边。'
			},
			{
				pic1:'/tpl/home/good/common/images/34/1.jpg',
				pic2:'/tpl/home/good/common/images/34/2.jpg',
				code:'/tpl/home/good/common/images/34/code.jpg',
				text:'长沙市酷琪ktv是一家健康、休闲、娱乐、聚会的时尚大众化场所，内设平价酒水超市，以崭新富有个性化的装潢、国际一流的硬件设施、震撼的音响、全新的触摸点歌系统、高档的液晶电视及独特新颖的经营理念，全新的量版式服务方式为宾客提供五星级服务。'
			},
			{
				pic1:'/tpl/home/good/common/images/35/1.jpg',
				pic2:'/tpl/home/good/common/images/35/2.jpg',
				code:'/tpl/home/good/common/images/35/code.jpg',
				text:'菲梵瑜伽肚皮舞会馆是国际注册职业技术认证中心（IRSC）在云南地区唯一指定的瑜伽教练及肚皮舞教练培训辅导圣地中心。本着为您带来健康和快乐的思想理念开设了这样一所最专业、最细腻、最人性化的家庭式私教瑜伽肚皮舞会馆。一同在这里远离城市的嘈杂与喧嚣，感受家庭式私密专业细致的美丽课堂！'
			}
		]
	},
	15:{//美容美妆
		navI:[
			{
				pic:'/tpl/home/good/common/images/28/logo.jpg',
				name:'太阳升化妆品'
			},
			{
				pic:'/tpl/home/good/common/images/37/logo.jpg',
				name:'昆明完美'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/28/1.jpg',
				pic2:'/tpl/home/good/common/images/28/2.jpg',
				code:'/tpl/home/good/common/images/28/code.jpg',
				text:'       太阳升化妆品公司创立于2000年，经过多年的发展，已经发展成集美容美发足疗按摩于一体的多元化公司。公司主要经营美容美体、祛斑、祛痘、减肥、黑头一抹净、抗衰、精油、毛发移植、微创整形等产品销售、免费技术培训。'
			},
			{
				pic1:'/tpl/home/good/common/images/37/1.jpg',
				pic2:'/tpl/home/good/common/images/37/2.jpg',
				code:'/tpl/home/good/common/images/37/code.jpg',
				text:'完美云南分公司成立于2004年7月16日，办公面积约450平米。云南分公司在总公司一贯的经营理念指导下，致力于“守法经营，规范运作，服务顾客，力求完美”的发展方向，以良好的服务品质和高度的责任心赢得社会的广泛认同。'
			}
		]
	},
	16:{//汽车
		navI:[
			{
				pic:'/tpl/home/good/common/images/32/logo.jpg',
				name:'曲靖上海大众'
			},
			{
				pic:'/tpl/home/good/common/images/38/logo.jpg',
				name:'汽车公众-autolife'
			},
			{
				pic:'/tpl/home/good/common/images/40/logo.jpg',
				name:'荆门讯隆丰田'
			},
			{
				pic:'/tpl/home/good/common/images/44/logo.jpg',
				name:'中升靖通（东风日产）'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/32/1.jpg',
				pic2:'/tpl/home/good/common/images/32/2.jpg',
				code:'/tpl/home/good/common/images/32/code.jpg',
				text:'云南曲靖麒麟物资有限公司成立于1973年，公司注册资金3000万元，经营地址位于曲靖市麒麟区子午路中段及曲靖龙华大道西侧太平村旁，共有员工300余人，是曲靖市首家上海大众汽车特许销售商。'
			},
			{
				pic1:'/tpl/home/good/common/images/38/1.jpg',
				pic2:'/tpl/home/good/common/images/38/2.jpg',
				code:'/tpl/home/good/common/images/38/code.jpg',
				text:'昆明汽车生活圈，实用汽车生活方式！'
			},
			{
				pic1:'/tpl/home/good/common/images/40/1.jpg',
				pic2:'/tpl/home/good/common/images/40/2.jpg',
				code:'/tpl/home/good/common/images/40/code.jpg',
				text:'一汽丰田、进口丰田品牌汽车销售。为您提供经营品牌的最新车型报价、新车到店图片等相关信息。'
			},
			{
				pic1:'/tpl/home/good/common/images/44/1.jpg',
				pic2:'/tpl/home/good/common/images/44/2.jpg',
				code:'/tpl/home/good/common/images/44/code.jpg',
				text:'曲靖中升靖通汽车销售服务有限公司是以品牌汽车销售及维修服务为主营业务的专业公司。公司是云南省贰类汽车维修企业，可进行各类维修作业及保修索赔。车辆年检、美容、装饰、保险理赔、二手车置换等特色服务可满足顾客的不同需求。'
			}
		]
	},
	17:{//投资理财
		navI:[
			{
				pic:'/tpl/home/good/common/images/42/logo.jpg',
				name:'海富贵金属'
			}
		],
		main:[
			{
				pic1:'/tpl/home/good/common/images/42/1.jpg',
				pic2:'/tpl/home/good/common/images/42/2.jpg',
				code:'/tpl/home/good/common/images/42/code.jpg',
				text:'       国内领先的贵金属服务专家，提供权威的市场分析，业内顶级专家“一站式”投资服务，7*24小时客服绿色通道，投资沙龙活动，名师授业。富贵生活，尽在福贵金属！'
			}
		]
	}
}