typeof Mugeda=="undefined"&&(Mugeda={});Mugeda.data=Mugeda.data||{};Mugeda.script=Mugeda.script||[];Mugeda.customScript="";Mugeda.scene=void 0;Mugeda.mapFrameNameId=Mugeda.mapFrameNameId||[];Mugeda.unzipAniData=function(a){a=MugedaCompress.unzip(a);if(a.script&&a.script.length)a.script=unescape(a.script);return a};Mugeda.getFrameLength=function(a){for(var d=1,c=a.length-1;c>=0;c--)for(var e=a[c],g=e.units.length,f=0;f<g;f++){var l=e.units[f],l=l.frameStart+l.frameCount;d<l&&(d=l)}return d};
Mugeda.getWindowSize=function(){var a=document.documentElement,d=a&&a.clientHeight===0;if(typeof document.clientWidth=="number")return{width:document.clientWidth,height:document.clientHeight};else{if(!d){var d=document,c=d.createElement("div");c.style.height="2500px";d.body.insertBefore(c,d.body.firstChild);var e=d.documentElement.clientHeight>2400;d.body.removeChild(c);d=e}if(d)a=document.body;return{width:a.clientWidth,height:a.clientHeight}}};
Mugeda.updateViewport=function(a,d,c,e){if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){if(c){var g=c.aniData.metadata?c.aniData.metadata.adaptMode:null;if(g=="none"||g==null)if(c.aniData.metadata=c.aniData.metadata||{},g=c.aniData.metadata.adaptMode=e?"none_mobile":"none_pc",!e)document.body.style.overflow="auto";if("contain,cover,width,width2,height,none_mobile,none_pc,fill".split(",").indexOf(g)>-1)a=document.createElement("div"),c.dom.style.position=
"absolute",c.dom.style.overflow="hidden",c.dom.style.left="0",c.dom.style.top="0",c.dom.style.right="0",c.dom.style.bottom="0",c.dom.style.margin="auto",c.dom.appendChild(a),c.dom=a}if(g==="width2")document.body.style.overflow="auto";document.documentElement.style.height="100%";document.body.style.height="100%"}};Mugeda.getCanvas=function(){return document.getElementsByClassName("MugedaStage")[0]};Mugeda.randPlus=0;
Mugeda.guidGen=function(){var a=new Date-new Date("2012/1/1")+""+Math.random().toString().substr(2,4);return Number(a).toString(36)+""+Mugeda.randPlus++};Mugeda.getMugedaObject=function(){return Mugeda.scene};Mugeda.loadUrl=function(a){return MugedaMraid.loadUrl(a)};Mugeda.enable3DRendering=function(a){a==void 0&&(a=false);this.threeDRendering=a};Mugeda.showFPS=function(){Mugeda.FPSMeter=true};Mugeda.enableNonDisplay=function(a){a==void 0&&(a=false);this.nonDisplay=a};
Mugeda.enableFlexibleFrameRate=function(a){a==void 0&&(a=false);this.flexibleFrameRate=a};Mugeda.enablePulseAnimation=function(a){a==void 0&&(a=false);Mugeda.enablePulse=a};
Mugeda.log=function(a){if(!Mugeda.logConsole)Mugeda.logConsole=document.createElement("div"),Mugeda.logConsole.style.display="block",Mugeda.logConsole.style.position="fixed",Mugeda.logConsole.style.background="#000",Mugeda.logConsole.style.color="#FFF",Mugeda.logConsole.style.left=0,Mugeda.logConsole.style.top=0,document.body.appendChild(Mugeda.logConsole);if(typeof a=="string"||a)Mugeda.logConsole.innerHTML=a;return Mugeda.logConsole.innerHTML};Mugeda.getAudioCache=function(a,d){return Mugeda.currentAni.audioBeList[d]};
Mugeda.setTextAsFlexbox=function(){this.textAsFlexbox=true};
window.MugedaCss3=function(a){if(!a){Mugeda.customScript="";var d=function(a){if(/^<.+>$/.test(a))return document.createElement(a.match(/^<(.+)>$/)[1]);else if(/^#.+/.test(a))return document.getElementById(a.match(/^#(.+)/)[1])};d.stage={};d.getAnimation=function(a){return d.stage[a]};d.initAnimation=function(a,d,c,b,m){a=new e(a,d,c,b);Mugeda.currentAni=a;document.dispatchEvent&&(d=document.createEvent("Events"),d.initEvent("mugedaReady",true,true),document.dispatchEvent(d));a.initDom(m);return a};
d.getCssBackgroundColor=function(a){var j=a.fillInfo;if(j.fillStyle==0)return"rgba("+j.fillColors[0].r+","+j.fillColors[0].g+","+j.fillColors[0].b+","+j.fillColors[0].a+")";else if(j.fillStyle==1||j.fillStyle==2){var c=j.fillStartPos.x,b=j.fillStartPos.y,e=j.fillEndPos.x,f=j.fillEndPos.y,g=a.rawWidth||a.width,l=a.rawHeight||a.height,a=Math.atan2(f-b,e-c),s=function(a,b,h){return{x:a*Math.cos(h)-b*Math.sin(h),y:a*Math.sin(h)+b*Math.cos(h)}},n=s(0,l,-a).x,u=s(g,l,-a).x,o=s(g,0,-a).x,r=s(c,b,-a).x,q=
s(e,f,-a).x,w=Math.max(0,n,u,o),x=Math.min(0,n,u,o),n=function(a,b,h){var d={};d.pm=h;d.r=(b.r-a.r)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.r);d.g=(b.g-a.g)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.g);d.b=(b.b-a.b)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.b);d.a=(b.a-a.a)/(b.pm-a.pm)*(h-a.pm)+parseFloat(a.a);return d},s=function(a,b){return"rgba("+Math.round(a.r)+","+Math.round(a.g)+","+Math.round(a.b)+","+a.a+") "+(b==void 0?a.pm:b)+"%"};if(j.fillStyle==1){j.fillColors.m_operate(function(a){a.pm=100/(w-x)*(r+(q-r)*
a.p-x)+0});for(var c=false,v="",e=0;e<j.fillColors.length;e++)if(b=j.fillColors[e],g=b.pm,c)if(g<100){if(v+=", "+s(b),e==j.fillColors.length-1){v+=", "+s(b,100);break}}else{v+=", "+s(n(b,j.fillColors[e-1],100),100);break}else{if(g<0)if(e<j.fillColors.length-1)if(j.fillColors[e+1].pm<0)continue;else v+=", "+s(n(b,j.fillColors[e+1],0));else v+=", "+s(b,0),v+=", "+s(b,100);else v+=", "+s(b,0),v+=", "+s(b);c=true}v="linear-gradient("+(d.browser.msie?a*180/Math.PI+90:-a*180/Math.PI)+"deg"+v+")"}else if(j.fillStyle==
2){a=Math.sqrt(Math.pow(c-e,2)+Math.pow(b-f,2));v="";for(e=0;e<j.fillColors.length;e++)v+=", "+s(j.fillColors[e],j.fillColors[e].p*100);v="radial-gradient("+c/g*100+"% "+b/l*100+"%, "+a+"px "+a+"px"+v+")"}return d.css3Per?d.css3Per.toLowerCase()+v:v}else return"transparent"};d.handleCapture=function(a){if(!a.redirected&&d.captureObject!=null){var j=document.createEvent("MouseEvents");j.initMouseEvent(a.type,true,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,
a.shiftKey,a.metaKey,a.button,a.relatedTarget);j.redirected=true;d.captureObject.object.dispatchEvent(j);a.type=="mouseup"&&d.captureObject&&d.captureObject.object.m_releasecapture()}};d.getCurrentStyle=function(a,d){if(document.defaultView){var c=document.defaultView.getComputedStyle(a,null);return c?c.getPropertyValue(d):null}else return a.currentStyle[d]};d.getEventPosition=function(a,c,e,b){var f,e=e||1;if(a.changedTouches&&(a=a.changedTouches[0],a==null))return null;f=a.clientX;a=a.clientY;if(c){for(var g=
c,p=0,l=0;g&&g.tagName!="BODY";)p+=g.offsetTop,l+=g.offsetLeft,g=g.offsetParent;f=f-l+window.pageXOffset-parseInt(d.getCurrentStyle(c,"border-left-width"));a=a-p+window.pageYOffset-parseInt(d.getCurrentStyle(c,"border-top-width"))}b&&(f/=e,a/=e);return{x:f,y:a}};d.escapeHTML=function(){var a={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"},d=/[&<>"'\/]/g;return function(c){return(""+c).replace(d,function(b){return a[b]})}}();var c=window;(function(){var a=c.performance;d.getTime=
a&&(a.now||a.webkitNow)?a[a.now?"now":"webkitNow"].bind(a):function(){return+new Date}})();a=navigator.userAgent.toLowerCase();a={version:(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1],safari:/webkit/.test(a),opera:/opera/.test(a),msie:(/msie/.test(a)||/trident/.test(a))&&!/opera/.test(a),mozilla:/mozilla/.test(a)&&!/(compatible|webkit)/.test(a)&&!/trident/.test(a)};d.browser=a;if(a.safari)d.css3Per="-webkit-",d.css3PerH="webkit";else if(a.opera)d.css3Per="-o-",d.css3PerH="o";else if(a.msie)d.css3Per=
"",d.css3PerH="";else if(a.mozilla)d.css3Per="-moz-",d.css3PerH="Moz";var e=function(a,d,c,b){this.aniData=a=a.zip?Mugeda.unzipAniData(a):a;this.title=a.title;this.width=a.width;this.height=a.height;this.dom=c;this.rate=a.rate;this.frameTime=1E3/a.rate;this.frameTimeString=this.frameTime+"ms";this.sceneHash={};this.mainSceneFrameUnitHash={};this.zoneCached={};this.event={};this.stopRedraw=false;this.resDir=b;this.scriptFile="string"==typeof d?d:null;this.frameParamCache={};this.paramUpdatePool={};
this.audioList={};this.scriptList=[]};e.prototype.getScene=function(){return this.scene};var g={mousedown:1,mouseup:1,click:1,dblclick:1,mouseover:1,mouseout:1,mousemove:1,touchstart:1,touchmove:1,touchend:1,inputstart:2,inputmove:2,inputend:2},f=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i);
window.navigator.userAgent.indexOf("Android");var l=function(a,c,e){a=="inputstart"?a=f?"touchstart":"mousedown":a=="inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){var b=this,m={fun:c,dir:function(a){a.postionGotton=false;a.inputX==void 0&&(Object.defineProperty(a,"inputX",{get:function(){return d.getEventPosition(a,b.thisAni.scene.dom,b.thisAni.overAllScaleX,b.thisAni).x}}),Object.defineProperty(a,"inputY",{get:function(){return d.getEventPosition(a,
b.thisAni.scene.dom,b.thisAni.overAllScaleY,b.thisAni).y}}));c.call(b,a)}};this.event[a]?this.event[a].push(m):this.event[a]=[m];this.dom.addEventListener(a,m.dir,e||false)}else this.event[a]?this.event[a].push(c):this.event[a]=[c];return this},x=function(a,d,c){a=="inputstart"?a=f?"touchstart":"mousedown":a=="inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){if(this.event[a]){for(var b=this.event[a].length-1;b>=0;b--)this.event[a][b].fun&&this.event[a][b].fun==
d&&(this.dom.removeEventListener(a,this.event[a][b].dir,c||false),this.event[a].splice(b,1));this.event[a].length==0&&delete this.event[a]}}else if(this.event[a]){for(b=this.event[a].length-1;b>=0;b--)this.event[a][b]==d&&this.event[a].splice(b,1);this.event[a].length==0&&delete this.event[a]}return this},o=function(a,d,c,b,e){if(this.event[a]){for(var f=[],g=0;g<this.event[a].length;g++)f[g]=this.event[a][g];for(g=0;g<f.length;g++)f[g].call(this,d,c,b,e)}};e.prototype.addEventListener=l;e.prototype.removeEventListener=
x;e.prototype.initDom=function(a){if(this.aniData&&this.dom){this.thisAni=this;this.countDownRef=0;this.imageCache=[];this.maxNum=0;Mugeda.updateViewport(this.aniData,null,this,f);this.loadOver=a;var c=this.aniData,g=this.dom,b=this;setTimeout(function(){window.scroll(0,0)},0);b.iOS=function(){var a={};if(/iP(hone|od|ad)/.test(navigator.platform)){var b=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);a.version=parseInt(b[1],10)+0.1*parseInt(b[2],10)}return a}();var m=function(a){var b=null;window.weixinAudioLoader&&
window.weixinAudioLoader[a]?b=window.weixinAudioLoader[a]:(b=new Audio(a),b.load());b.addEventListener("ended",function(){b.loop?(b.currentTime=0,b.play()):b.currentTime=0});return b},t=function(a,d,c,E,e,h,i,j,g){this.id=a;this.data=d;this.length=Mugeda.getFrameLength(d.layers);this.playing=c;this.currentId=null;this.nextId=0;this.offset=e;this.dom=h;this.layerList=[];this.objectHash={};this.unitHash=[];this.isSymbol=i;this.clickEventAttached={};this.nameHash={};this.scriptHash={};this.segment={};
this.currentSegment={};b.sceneHash[this.id]=this;this.event={};this.frameout=[];this.thisAni=b;this.parentScene=j;this.cachedVisibility={};this.lastRenderList={};this.frameLength=0;if(i)this.object=g;a=i?d.id:"_main";b.frameParamCache[a]=b.frameParamCache[a]||{};this.frameParamCache=b.frameParamCache[a]};t.prototype.getFrameId=function(a,b){var d=a.toString(),c=this.id=="_main"?"":this.id+"_";d.match(/^\d+$/)?d=parseInt(d):(keyId=c+d,d=Mugeda.mapFrameNameId[keyId],d=parseInt(d)+(b?1:0));return d};
t.prototype.getObjectByName=function(a){return this.nameHash[a]};t.prototype.initAndGetDom=function(){var a=this;a.data.layers.m_operate(function(b){b=new p(b,a);a.layerList.push(b);b.initAndGetDom(a.dom)},true)};t.prototype.play=function(){this.playing=true;b.stopRedraw=false;return this};t.prototype.pause=function(){this.pauseFlag=true;this.playing=false;o.call(this,"pause");return this};t.prototype.gotoAndPlay=function(a,b){this.gotoFlag=true;this.nextId=this.getFrameId(a,b)-(b?1:0);return this.play()};
t.prototype.gotoAndPause=function(a,b){this.nextId=this.getFrameId(a,b)-(b?1:0);this.gotoFlag=true;return this.pause()};t.prototype.setSegment=function(a,b,d,c){this.segment[a]={from:Math.min(b,this.length),to:Math.min(d,this.length),isLoop:c};return this};t.prototype.playSegment=function(a){(this.currentSegment=this.segment[a])&&this.gotoAndPlay(this.currentSegment.from);return this};t.prototype.setFrameout=function(a,b){for(var d=this.frameout.length,c=0,e=0;e<this.frameout.length;e++){var h=this.frameout[e];
if(c+h.time>a){d=e;break}c+=h.time}this.frameout.splice(d,0,{time:a-c,fun:b});return this};t.prototype.removeChild=function(a){if(a.unit){var b=a.unit.data.objects;if(a.parentGroup)b=a.parentGroup.data;b.m_operate(function(d,c){if(d.guid==a.id)return b.splice(c,1),false})}a.dom.parentNode.removeChild(a.dom);this.nameHash[a.name]&&delete this.nameHash[a.name];delete this.objectHash[a.id];if(this.scriptHash[a.id])delete this.scriptHash[a.id];else{var d=a.unit?a.unit.data.frameStart:0,c=a.unit?a.unit.data.frameStart+
a.unit.data.frameCount-1:a.currentScene.frameLength-1,e=this.cachedVisibility;setTimeout(function(){for(var b=d;b<=c;b++)for(var i=e[b].length,h=0;h<i;h++)if(e[b][h].id==a.id){e[b].splice(h,1);break}},0)}return this};t.prototype.appendChild=function(a,b){if(a.name&&this.nameHash[a.name])throw"object name: "+a.name+" had been used";this.nameHash[a.name]=a;for(var d=0;d<(this.frameLength||1);d++)this.cachedVisibility[d]=this.cachedVisibility[d]||[],this.cachedVisibility[d].push(a);a.currentScene=this;
a.initAndGetDom(this.dom,b&&b.dom?b.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};t.prototype.addEventListener=l;t.prototype.removeEventListener=x;var p=function(a,b){this.id=a.id;this.name=a.name;this.data=a;this.unitList=[];this.scene=b};p.prototype.initAndGetDom=function(a){var b=this;b.data.units.m_operate(function(d){d=new r(d,b);b.unitList.push(d);d.initAndGetDom(a)},true)};var r=function(a,b){this.data=a;this.layer=b;this.objectList=[];this.symbolList=[];
this.imageList=[];this.id=a.id;b.scene.unitHash[a.id]=this;b.scene.frameParamCache[this.id]=b.scene.frameParamCache[this.id]||{};this.cachedFrame=b.scene.frameParamCache[this.id];this.zoneCached=false};r.prototype.initAndGetDom=function(a){var d=this,c=this.layer.scene;if(this.data&&(this.data.audio||this.data.audioId))this.audio=this.data.audioId?m(b.audioSym[this.data.audioId]):m(b.resDir+this.data.audio);if(this.audio){for(var e=Mugeda.guidGen(),h=this.data.frameStart;h<this.data.frameStart+this.data.frameCount;h++)c.cachedAudio=
c.cachedAudio||[],c.cachedAudio[h]=c.cachedAudio[h]||[],c.cachedAudio[h].push({audio:this.audio,start:h==this.data.frameStart,hash:e});b.audioList[e]=this.audio}if(!this.data.objects||this.data.objects.length==0){if(e=this.data.keyframes[0],e.name){var h=e.name,y=h.indexOf("_")+1,h=h.substr(y),h=(c.id=="_main"?"":c.id+"_")+h;Mugeda.mapFrameNameId[h]=e.id}}else{if(this.data.keyframes.length)this.data.hashKey={},this.data.keyframes.m_operate(function(a){d.data.hashKey["key_"+a.id]=a;if(a.name){var b=
a.name,h=b.indexOf("_")+1,b=b.substr(h),b=(c.id=="_main"?"":c.id+"_")+b;Mugeda.mapFrameNameId[b]=a.id}});this.data.objects.m_operate(function(b){b=new n(b,d);d.objectList.push(b);b.initAndGetDom(a);if(b.symbolIdList)d.symbolList=d.symbolList.concat(b.symbolIdList);Mugeda.nonDisplay?b.hide():b.dom.style.cssText+="display:none;"});c=this.layer.scene;for(h=this.data.frameStart;h<this.data.frameStart+this.data.frameCount;h++)c.cachedVisibility[h]=c.cachedVisibility[h]||[],c.cachedVisibility[h]=c.cachedVisibility[h].concat(this.objectList);
c.frameLength=Math.max(c.frameLength,this.data.frameStart+this.data.frameCount);if(this.layer.scene.id=="_main")for(h=this.data.frameStart;h<this.data.frameStart+this.data.frameCount;h++)b.mainSceneFrameUnitHash[h]=b.mainSceneFrameUnitHash[h]||[],b.mainSceneFrameUnitHash[h].push(this)}};r.prototype.updateUnitVisibility=function(a){this.objectList.m_operate(function(b){Mugeda.nonDisplay?a?b.show():b.hide():b.dom.m_css("display",a?b.dom.displayType||"block":"none")})};var s=function(a,b,d,c){this.parent=
a;this.dom=b;this.data=a.data.items;this.objectList=[];this.unit=d;this.scene=c};s.prototype.initAndGetDom=function(){var a=this;this.data.length!=0&&this.data.m_operate(function(b){b=new n(b,a.unit,{inGroup:true,group:a});if(!b.currentScene)b.currentScene=a.scene;a.objectList.push(b);b.initAndGetDom(a.dom)})};var n=MugedaCss3.aObject=function(a,d,c){c=c||{};a=this.data=JSON.parse(JSON.stringify(a));this.currentScene=(this.unit=d)?d.layer.scene:null;this.id=Mugeda.guidGen();d&&(this.currentScene.nameHash[a.param.name]=
this);if(c.inGroup)this.offset={x:0,y:0},this.parentGroup=c.group;this.event={};this.thisAni=b;this.userParam={};var h=[],e=[],y=function(a){if(a.items)for(var b=0;b<a.items.length;b++){var d=a.items[b];d.type==2021||d.type==2023?(d.symbolSceneId=Mugeda.guidGen(),h.push(d.symbolSceneId),e.push(d.param.symbolId)):a.type==2014&&y(d)}};if(!c.inGroup)if(a.type==2014)y(a);else if(a.type==2021||a.type==2023)a.symbolSceneId=Mugeda.guidGen(),h.push(a.symbolSceneId),e.push(a.param.symbolId);if(h.length)this.symbolList=
h,this.symbolIdList=e;Object.defineProperty(this,"name",{get:function(){return this.data.param.name},set:function(a){if(this.currentScene.nameHash[a])throw"name had been used before";this.currentScene.nameHash[a]=this.currentScene.nameHash[this.data.param.name];delete this.currentScene.nameHash[this.data.param.name];this.data.param.name=a}});a.type==2005&&Object.defineProperty(this,"src",{get:function(){return this.userParam.src},set:function(a){this.userParam.src=a;this.dom.tagName=="DIV"?this.dom.childNodes[0].src=
a:this.dom.src=a}});Object.defineProperty(this,"width",{get:function(){return this.data.param.width},set:function(a){var b=this.data.param.width/this.scaleX,d=this.rotateCenterX/this.scaleX;this.rotateCenterX=0;this.scaleX=a/b;this.rotateCenterX=d*this.scaleX}});Object.defineProperty(this,"height",{get:function(){return this.data.param.height},set:function(a){var b=this.data.param.height/this.scaleY,d=this.rotateCenterY/this.scaleY;this.rotateCenterY=0;this.scaleY=a/b;this.rotateCenterY=d*this.scaleY}});
Object.defineProperty(this,"left",{get:function(){return this.data.param.left},set:function(a){this.userParam.x=a-this.userParam.ox+this.userParam.rx;this.data.param.left=a;this.data.param.right=this.data.param.left+this.data.param.width;z(this)}});Object.defineProperty(this,"right",{get:function(){return this.data.param.right},set:function(a){this.data.param.right=a;this.data.param.left=a-this.data.param.width;this.userParam.x=this.data.param.left-this.userParam.ox+this.userParam.rx;z(this)}});Object.defineProperty(this,
"top",{get:function(){return this.data.param.top},set:function(a){this.data.param.top=a;this.userParam.y=a-this.userParam.oy+this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;z(this)}});Object.defineProperty(this,"bottom",{get:function(){return this.data.param.bottom},set:function(a){this.data.param.bottom=a;this.data.param.top=a-this.data.param.height;this.userParam.y=this.data.param.top-this.userParam.oy+this.userParam.ry;z(this)}});Object.defineProperty(this,"x",
{get:function(){return this.userParam.x},set:function(a){this.userParam.x=a;this.data.param.left=a+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;z(this)}});Object.defineProperty(this,"y",{get:function(){return this.userParam.y},set:function(a){this.userParam.y=a;this.data.param.top=a+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;z(this)}});Object.defineProperty(this,"rotateCenterX",{get:function(){return this.userParam.rx},
set:function(a){this.data.param.rotateCenterX=this.userParam.rx=Math.round(a);this.userParam.rsx=a/this.userParam.sx;this.userParam.x=this.data.param.left+a-this.userParam.ox;z(this)}});Object.defineProperty(this,"rotateCenterY",{get:function(){return this.userParam.ry},set:function(a){this.data.param.rotateCenterY=this.userParam.ry=Math.round(a);this.userParam.rsy=a/this.userParam.sy;this.userParam.y=this.data.param.top+a-this.userParam.oy;z(this)}});Object.defineProperty(this,"scaleX",{get:function(){return this.userParam.sx},
set:function(a){this.userParam.rx=this.data.param.rotateCenterX=this.userParam.rx/this.userParam.sx*a;this.userParam.sx=this.data.param.scaleX=a;this.data.param.width=this.data.param.rawWidth*a;this.data.param.left=this.userParam.x+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;z(this)}});Object.defineProperty(this,"scaleY",{get:function(){return this.userParam.sy},set:function(a){this.userParam.ry=this.data.param.rotateCenterY=this.userParam.ry/
this.userParam.sy*a;this.userParam.sy=this.data.param.scaleY=a;this.data.param.height=this.data.param.rawHeight*a;this.data.param.top=this.userParam.y+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;z(this)}});Object.defineProperty(this,"rotate",{get:function(){return this.data.param.rotate},set:function(a){this.data.param.rotate=a;z(this)}});Object.defineProperty(this,"alpha",{get:function(){return this.data.param.alpha},set:function(a){this.data.param.alpha=
a;z(this)}});this.userParam.visible=true;Object.defineProperty(this,"visible",{get:function(){return this.userParam.visible},set:function(a){(this.userParam.visible=a)?this.dom.m_css("display",this.dom.m_attr("displayType")||"block",b):this.dom.m_css("display","none",b)}});Object.defineProperty(this,"text",{get:function(){if(this.data.type==2010)return unescape(this.data.param.textContent)},set:function(a){if(this.data.type==2010)this.data.param.textContent=escape(a);z(this)}});Object.defineProperty(this,
"url",{get:function(){},set:function(a){this.data.param.url=a}})},u={},w=function(){delete u.old;for(objId in u)u[objId].updateObjectParam();u={}},z=function(a){u[a.id]=a;u.old=true;setTimeout(w,0)};n.prototype.setCapture=function(a){this.dom.m_setCapture(a)};n.prototype.releaseCapture=function(a){this.dom.m_releasecapture(a)};n.prototype.initAndGetDom=function(a,c){var h=this.data,e;if(h.param.left===null)this.unit&&this.unit.data.keyframes&&this.unit.data.keyframes.length>=2?h.param=JSON.parse(JSON.stringify(this.unit.data.keyframes[0].param)):
console.log("Fatal error: object (ID: "+h.guid+") param is lost!");var j=false;if(this.currentScene&&this.currentScene.cachedSymbolScene)var j=true,y=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[h.guid].dom.className)[0];var i=h.param;switch(h.type){case 2003:case 2004:case 2009:if(j)break;var g=i.lineWidth,f=Math.floor(i.lineWidth/2);e=d("<div>");var k=d("<div>");k.m_addClass("guid_"+Mugeda.guidGen());g&&k.m_css("border",g+"px solid "+i.strokeColor).m_css("position",
"absolute").m_css("top",-f+"px").m_css("bottom",-f+"px").m_css("left",-f+"px").m_css("right",-f+"px").m_appendTo(e);if(h.type==2009){var m=h.cornerRadius[0]+"px ";e.m_css("border-radius",m+m+m+m);e.m_css("border-top-left-radius",m);e.m_css("border-top-right-radius",m);e.m_css("border-bottom-left-radius",m);e.m_css("border-bottom-right-radius",m)}else if(h.type==2004){var m=i.width/2+"px",p=i.height/2+"px";e.m_css("border-radius",m+" "+p);e.m_css("border-top-left-radius",m+" "+p);e.m_css("border-top-right-radius",
m+" "+p);e.m_css("border-bottom-left-radius",m+" "+p);e.m_css("border-bottom-right-radius",m+" "+p)}e.m_css("background",d.getCssBackgroundColor(i));g&&(h.type==2009?(m=h.cornerRadius[0]+f+"px ",k.m_css("border-radius",m+m+m+m),k.m_css("border-top-left-radius",m),k.m_css("border-top-right-radius",m),k.m_css("border-bottom-left-radius",m),k.m_css("border-bottom-right-radius",m)):h.type==2004&&(m=i.width/2+f+"px",p=i.height/2+f+"px",k.m_css("border-radius",m+" "+p),k.m_css("border-top-left-radius",
m+" "+p),k.m_css("border-top-right-radius",m+" "+p),k.m_css("border-bottom-left-radius",m+" "+p),k.m_css("border-bottom-right-radius",m+" "+p)));break;case 2005:if(!i.imageSrc.length)i.imageSrc="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(i.imageSrc.length>0){this.userParam=this.userParam||[];this.userParam.src=(i.imageSrc.indexOf("data:")==0?"":b.resDir)+i.imageSrc;if(j){g=y;y.tagName=="DIV"&&(g=y.childNodes[0]);b.loadImage("dom_back",{dom:g,url:b.resDir+
i.imageSrc,duringBuilding:b.zoneCachedMode,scene:this.currentScene,unit:this.unit});break}e=d("<img>");if(i.keepAspect){var g=i.rawWidth,f=i.rawHeight,k=i.width,m=i.height,p=k/g*f,n=k,l=n=0;p>m?(p=m,n=(k-m/f*g)/2,e.m_css("padding-left",n.toString()+"px"),e.m_css("padding-right",n.toString()+"px")):(l=(m-p)/2,e.m_css("padding-top",n.toString()+"px"),e.m_css("padding-bottom",n.toString()+"px"))}b.loadImage("dom_back",{dom:e,url:(i.imageSrc.indexOf("data:")==0?"":b.resDir)+i.imageSrc,duringBuilding:b.zoneCachedMode,
scene:this.currentScene,unit:this.unit})}break;case 2010:if(Mugeda.textAsFlexbox){if(j){y.displayType="";break}e=d("<div>");g=d("<div>").m_appendTo(e).m_css("width","100%");g.innerHTML=unescape(i.textContent).replace(/\n/g,"<br>").replace(/\s\s/g," &nbsp;");g.txt=i.textContent;e.m_css("font-size",i.fontSize+"px").m_css("font-weight",i.fontWeight).m_css("font-family",i.fontFamily).m_css("text-stroke",i.lineWidth/2+"px "+i.strokeColor).m_css("text-shadow","0 "+(i.lineWidth/2<1?1:i.lineWidth/2)+"px "+
i.strokeColor).m_css("line-height",parseInt(i.fontSize)+4+"px").m_css("text-align",i.textAlign||"left").m_css("text-fill-color",d.getCssBackgroundColor(i)).m_css("color","rgba("+i.fillInfo.fillColors[0].r+","+i.fillInfo.fillColors[0].g+","+i.fillInfo.fillColors[0].b+","+i.fillInfo.fillColors[0].a+")").m_css("padding-top","1px").m_addClass("flex").m_addClass(i.textVAlign);e.displayType=""}else{if(j){y.displayType="table";break}e=d("<div>");g=d("<div>").m_appendTo(e).m_css("display","table-cell").m_css("vertical-align",
i.textVAlign||"baseline");g.displayType="table-cell";g.innerHTML=d.escapeHTML(unescape(i.textContent)).replace(/\n/g,"<br>").replace(/\s/g," &nbsp;");g.txt=i.textContent;e.m_css("font-size",i.fontSize+"px").m_css("font-weight",i.fontWeight).m_css("font-family",i.fontFamily).m_css("display","table").m_css("text-stroke",i.lineWidth/2+"px "+i.strokeColor).m_css("text-shadow","0 "+(i.lineWidth/2<1?1:i.lineWidth/2)+"px "+i.strokeColor).m_css("line-height",parseInt(i.fontSize)+4+"px").m_css("text-align",
i.textAlign||"left").m_css("text-fill-color",d.getCssBackgroundColor(i)).m_css("color","rgba("+i.fillInfo.fillColors[0].r+","+i.fillInfo.fillColors[0].g+","+i.fillInfo.fillColors[0].b+","+i.fillInfo.fillColors[0].a+")").m_css("padding-top","1px");e.displayType="table"}i.fontStyle&&e.m_css("font-style",i.fontStyle);i.textDecoration&&e.m_css("text-decoration",i.textDecoration);break;case 2014:j?e=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[h.guid].dom.className)[0]:
(e=d("<div>"),e.m_addClass("group"));this.group=g=new s(this,e,this.unit,this.currentScene);g.initAndGetDom(e);break;case 2023:g=function(a){return{fillInfo:null,imageSrc:i.imageSrc,rawWidth:i.rawWidth,rawHeight:i.rawHeight*i.frameNum,left:0,right:i.rawWidth,top:-i.rawHeight*a,bottom:i.rawHeight*(i.frameNum-a),scaleX:1,scaleY:1,rotate:0,alpha:1,width:i.rawWidth,height:i.rawHeight*i.frameNum}};f=Mugeda.guidGen();k=Math.ceil(i.frameNum/i.fps*b.rate);b.symbols[f]={id:f,name:f,cw:b.aniData.width,ch:b.aniData.height,
layers:[{id:0,name:"\u56fe\u5c420",units:[{id:Mugeda.guidGen(),layerId:0,frameStart:0,frameCount:k,animated:true,objects:[{guid:Mugeda.guidGen(),type:2005,param:g(0)}],keyframes:[],hashKey:[],visible:true}]}]};m=null;for(p=0;p<k;p++){var u=Math.min(Math.round(p/b.rate*i.fps),i.frameNum-1);u!=m&&(b.symbols[f].layers[0].units[0].keyframes.push({id:p,mode:0,tween:"Step.EaseIn",param:g(u)}),m=u);b.symbols[f].layers[0].units[0].guessKeyframe=false}i.symbolId=f;i.offsetX=-b.aniData.width/2;i.offsetY=-b.aniData.height/
2;case 2021:if(!b.symbols[i.symbolId])break;g=b.symbols[i.symbolId];if(j)f=b.symbols[i.symbolId].cw/2+i.offsetX,k=b.symbols[i.symbolId].ch/2+i.offsetY,f=this.scene=new t(this.data.symbolSceneId,b.symbols[i.symbolId],true,0,{x:f,y:k},y,true,this.currentScene,this),f.cachedSymbolScene=this.currentScene.cachedSymbolScene.objectHash[h.guid].scene;else{e=d("<div>");e.m_addClass("symbol");h.type==2023&&e.m_css("overflow","hidden");f=b.symbols[i.symbolId].cw/2+i.offsetX;k=b.symbols[i.symbolId].ch/2+i.offsetY;
f=this.scene=new t(this.data.symbolSceneId,b.symbols[i.symbolId],true,0,{x:f,y:k},e,true,this.currentScene,this);if(h.type==2023){if(i.looped==null)i.looped=true;this.scene.looped=i.looped}if(g.cachedInstance)symCache=g.cachedInstance.scene,f.dom.innerHTML=symCache.dom.innerHTML,f.cachedSymbolScene=symCache}f.initAndGetDom();break;case 2024:if(g=JSON.parse(h.param.Form),e=d("<div>"),MugedaBehavior.popupForm(g,true),k=g.iframeDiv){k.style.padding=0;e.appendChild(k);var f=k.querySelectorAll(".inputlabel"),
k=k.querySelectorAll(".popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select"),o=g.hwObj;Array.prototype.forEach.call(f,function(a){a.style.width=o.l+"px"});Array.prototype.forEach.call(k,function(a){a.style.width=o.r+"px"})}}if(e||j)if(j)this.dom=y,this.currentScene.objectHash[h.guid]=this,this.updateObjectParam({staticMode:true,readyCachedMode:true,isImage:h.type==2005}),this.dom.object=this;else{e.m_addClass("layer_"+(this.unit?this.unit.layer.id:"script")).m_addClass("guid_"+
this.id).m_css("position","absolute").m_css("left",0).m_css("top",0).m_css("backface-visibility","hidden");if(i.vF||i.hF)j=d("<div>").m_css("position","absolute").m_append(e),e.m_css("top","0").m_css("left","0").m_css("right","0").m_css("bottom","0").m_css("transform",(i.vF?"scaleY(-1) ":"")+(i.hF?"scaleX(-1)":"")),e=j,j.className="guid_"+Mugeda.guidGen();a.m_append(e,c);this.dom=e;this.dom.object=this;this.currentScene.objectHash[h.guid]=this;this.updateObjectParam({staticMode:true,isImage:h.type==
2005,dw:n,dh:l});if(h.type===2024)e=e.firstChild,j=h.param.width,y=h.param.height,h=function(a,b,d,c){var h=a,e=b,A=1;a/b>d/c?(h=d,e=d*(b/a),A=d/a):(e=c,h=c/(b/a),A=c/b);return{w:h,h:e,mt:(c-e)/2,ml:(d-h)/2,r:A}}(288,MugedaBehavior.getPopupFormHeight(JSON.parse(h.param.Form)),j,y),e.parentNode.m_transform(0,0,null,1,1,0,0),e.m_transform(h.ml,h.mt,null,h.r,h.r,0,0)}};n.prototype.addEventListener=l;n.prototype.removeEventListener=x;n.prototype.getPath=function(){for(var a=this,b="";;){b=(a.name||"@"+
a.id)+"/"+b;if(!a.currentScene)return"~"+b.substr(0,b.length-1);if(a.currentScene.id=="_main")return b.substr(0,b.length-1);if(!a.currentScene.object)return"<-"+b.substr(0,b.length-1);a=a.currentScene.object}};n.prototype.setParam=function(a){a.call(this,this.param);this.updateObjectParam({param:this.param});Mugeda.nonDisplay?this.param.hide?this.hide():this.show():this.dom.m_css("display",this.param.hide?"none":this.dom.displayType!=null?this.dom.displayType:"block")};n.prototype.getParam=function(){this.param.hide=
this.param.hide||false;return this.param};n.prototype.setButton=function(a,b,d){var c=this.scene;c&&(d==void 0&&(d=a),typeof a=="number"&&(a={from:a,to:a,isLoop:false}),typeof b=="number"&&(b={from:b,to:b,isLoop:false}),typeof d=="number"&&(d={from:d,to:d,isLoop:false}),c.setSegment("__normal",a.from,a.to,a.isLoop),c.setSegment("__push",b.from,b.to,b.isLoop),c.setSegment("__up",d.from,d.to,d.isLoop),c.playSegment("__normal"),this.addEventListener("inputstart",function(){this.disabled||this.scene.playSegment("__push")}),
this.addEventListener("inputend",function(){this.scene.currentSegment==c.segment.__push&&this.scene.playSegment("__up")}),this.addEventListener("mouseout",function(){this.scene.currentSegment==c.segment.__push&&this.scene.playSegment("__up")}));this.dom.m_css("cursor","pointer");return this};n.prototype.appendChild=function(a,b){if(a.name&&this.currentScene.nameHash[a.name])throw"object name: "+a.name+" had been used";this.currentScene.nameHash[a.name]=a;for(var d=this.unit?this.unit.data.frameStart:
0,c=this.unit?d+this.unit.data.frameCount:this.currentScene.frameLength;d<c;d++)this.currentScene.cachedVisibility[d]=this.currentScene.cachedVisibility[d]||[],this.currentScene.cachedVisibility[d].push(a);a.currentScene=this.currentScene;a.initAndGetDom(this.dom,b&&b.dom?b.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};n.prototype.updateObjectParam=function(a){a=a||{};staticMode=a.staticMode||false;readyCachedMode=a.readyCachedMode||false;var c=this.dom,h=this.offset||
this.currentScene.offset,e=a.param||this.data.param,j=this;this.param=e;if(staticMode&&(a.isImage?(e.rawWidth=e.width-(a.dw?a.dw*2:0),e.rawHeight=e.height-(a.dh?a.dh*2:0)):(e.rawWidth=e.rawWidth||e.width,e.rawHeight=e.rawHeight||e.height),readyCachedMode||(c.m_width(e.rawWidth).m_height(e.rawHeight),(e.vF||e.hF)&&c.childNodes[0].m_width(e.rawWidth).m_height(e.rawHeight)),e.action))if(e.action=="link"&&e.url&&e.url.length){var g=function(){MugedaMraid.openLink(e.url,e.urlTarget)};c.m_css("cursor",
"pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(a){g();a.preventDefault();a.stopPropagation();return false})}else if(e.action=="form"&&e.form&&e.form.length)g=function(){MugedaBehavior.popupForm(JSON.parse(e.form))},c.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(a){g();a.preventDefault();a.stopPropagation();return false});else if(e.action=="behavior"&&e.behavior)a=JSON.parse(e.behavior),e.behaviorObj=a,a.m_operate(function(a){if(a.type==
"audio"){var d=a.param.audio_id?b.audioSym[a.param.audio_id]:b.resDir+a.param.audio_url;b.audioBeList=b.audioBeList||{};var c=Mugeda.guidGen();a.param.audioId=c;b.audioBeList[c]=m(d);if(a.param.audio_loop=="1")b.audioBeList[c].loop=true;a.param.audio_name&&(j.currentScene.nameHash[a.param.audio_name]=b.audioBeList[c]);b.audioList[c]=b.audioBeList[c]}});var a=e.width/e.rawWidth,i=e.height/e.rawHeight,k=e.rotateCenterX!=void 0?e.rotateCenterX:e.width/2,p=e.rotateCenterY!=void 0?e.rotateCenterY:e.height/
2,n=Math.round(k/a),l=Math.round(p/i),k=n*a,p=l*i,s=e.left-(n-k)-h.x,u=e.top-(l-p)-h.y,t=e.rotate;s.toString().indexOf("e")>-1&&(s=0);u.toString().indexOf("e")>-1&&(u=0);a.toString().indexOf("e")>-1&&(a=0);i.toString().indexOf("e")>-1&&(i=0);t.toString().indexOf("e")>-1&&(t=0);this.userParam.x=s+n;this.userParam.y=u+l;this.userParam.rx=k;this.userParam.ry=p;this.userParam.sx=a;this.userParam.sy=i;this.userParam.rsx=n;this.userParam.rsy=l;this.userParam.ox=h.x;this.userParam.oy=h.y;c.m_css("opacity",
Math.floor(100*e.alpha)*0.01,b).m_css("transform-origin",n.toString()+"px "+l.toString()+"px",b);this.beforeHiddenTrans="translate("+s.toString()+"px,"+u.toString()+"px) rotate("+t.toString()+"rad) scale("+a.toString()+","+i.toString()+")";this.hidden||c.m_css("transform",this.beforeHiddenTrans,b);if(e.textContent!=void 0&&c.childNodes[0].txt!=e.textContent)c.childNodes[0].innerHTML=d.escapeHTML(unescape(e.textContent)).replace(/\n/g,"<br>").replace(/\s/g," &nbsp;"),c.childNodes[0].txt=e.textContent};
n.prototype.hide=function(){if(!this.hidden)return this.dom.m_css("transform","translate(-9999999px, -99999999px)",b),this.hidden=true,this};n.prototype.show=function(){if(this.hidden)return this.beforeHiddenTrans&&this.dom.m_css("transform",this.beforeHiddenTrans,b),this.hidden=false,this};n.prototype.clone=function(a){var b=JSON.parse(JSON.stringify(this.data));b.param.name=a;b.guid=Mugeda.guidGen();return new n(b,null)};a=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(a);
b.externalStylesheet=a.sheet||a.styleSheet;b.indexedStylesheet={};b.cachedRule=[];this.dom.m_attr("name",c.title).m_addClass("MugedaStage").m_width(c.width).m_height(c.height).m_css("background-color",c.color).m_css("background-image",c.image?"url("+c.image+")":"").m_css("background-repeat","no-repeat").m_css("background-size",c.width+"px "+c.height+"px").m_css("overflow","hidden").m_css("position","relative");Mugeda.enablePulse&&this.dom.m_css("transform","translate(0,0)");this.dom.style.webkitTapHighlightColor=
"rgba(0,0,0,0)";b.loadingDiv=d("<div>").m_css("line-height",c.height+"px").m_css("text-align","center").m_css("background","black").m_css("color","white").m_css("font-family","arial");b.dom.insertBefore(b.loadingDiv,b.dom.firstChild);b.loadingDiv.innerHTML="Loading...";b.loadingDiv.id="loadingDiv";var q=b.dom,B=function(){b.adaption=b.adaption||{};if(typeof _mrmcp=="undefined"||_mrmcp.render_mode!="inline"&&_mrmcp.render_mode!="embedded"){var a=document.body.offsetWidth/c.width,d=document.body.offsetHeight/
c.height,d=document.body.offsetHeight/c.height,e=c.metadata?c.metadata.adaptMode:null,h=1,g=c.width,f=c.height;b.adaption.type=e;switch(e){case "contain":h=Math.max(0.001,Math.min(a,d));break;case "cover":h=Math.max(a,d,0.001);break;case "width":case "width2":case "none_mobile":h=Math.max(a,0.001);break;case "height":h=Math.max(d,0.001)}a=e=="fill"?a:h;d=e=="fill"?d:h;g*=a;f*=d;q.parentNode.style.width=g+"px";q.parentNode.style.height=f+"px";b.overAllScaleX=a;b.overAllScaleY=d;b.adaption.scale=h;
b.adaption.scaleX=a;b.adaption.scaleY=d;e=="width2"?b.adaption.marginLeft=b.adaption.marginRight=b.adaption.marginTop=b.adaption.marginBottom=0:(b.adaption.marginLeft=b.adaption.marginRight=(document.body.offsetWidth/a-c.width)/2,b.adaption.marginTop=b.adaption.marginBottom=(document.body.offsetHeight/d-c.height)/2);e=="none_mobile"||e=="none_pc"?(h=document.body.offsetHeight-c.height*d<0)?(b.adaption.marginTop=b.adaption.marginBottom=0,q.parentNode.style.marginTop="0",q.parentNode.style.marginBottom=
"0"):(q.parentNode.style.marginTop="auto",q.parentNode.style.marginBottom="auto"):e=="width2"?(q.parentNode.style.marginTop="0",q.parentNode.style.marginBottom="0"):(h=document.body.offsetHeight-c.height*d<0)?(q.parentNode.style.marginTop=-(c.height*d-document.body.offsetHeight)/2+"px",q.parentNode.style.marginBottom="0",q.parentNode.style.height="auto"):(q.parentNode.style.marginTop="auto",q.parentNode.style.marginBottom="auto",q.parentNode.style.height=f+"px");e=="none_pc"?document.body.offsetWidth-
c.width*a<0?(b.adaption.marginLeft=b.adaption.marginRight=0,q.parentNode.style.marginLeft="0"):q.parentNode.style.marginLeft="auto":(h=document.body.offsetWidth-c.width*a<0)?(q.parentNode.style.marginLeft=-(c.width*a-document.body.offsetWidth)/2+"px",q.parentNode.style.marginRight="0",q.parentNode.style.width="auto"):(q.parentNode.style.marginLeft="auto",q.parentNode.style.marginRight="auto",q.parentNode.style.width=g+"px");q.m_transform(null,null,null,a,d,0,0)}o.call(b,"resize",b.adaption)};B();
Mugeda.textAsFlexbox&&(b.insertRule(".flex.middle","-webkit-box-align: center;-moz-box-align: center;-ms-flex-align: center;-webkit-justify-content: center;-moz-justify-content: center;justify-content: center;-webkit-box-pack: center;-moz-box-pack: center;-ms-flex-pack: center;-webkit-align-items: center;-moz-align-items: center;align-items: center;"),b.insertRule(".flex","display: -webkit-box; display: -webkit-flex; display: -moz-box; display: -moz-flex; display: -ms-flexbox; display: flex;"),b.insertRule(".flex.top",
"-webkit-box-align: start;-moz-box-align: start;-ms-flex-align: start;-webkit-justify-content: start;-moz-justify-content: start;justify-content: flex-start;-webkit-box-pack: start;-moz-box-pack: start;-ms-flex-pack: start;-webkit-align-items: flex-start;-moz-align-items: flex-start;align-items: flex-start;"),b.insertRule(".flex.bottom","-webkit-box-align: end;-moz-box-align: end;-ms-flex-align: end;-webkit-justify-content: end;-moz-justify-content: end;justify-content: flex-end;-webkit-box-pack: end;-moz-box-pack: end;-ms-flex-pack: end;-webkit-align-items: flex-end;-moz-align-items: flex-end;align-items: flex-end;"));
b.updateRuleCached();b.loadProcess="script";if(b.aniData.sL)if(Mugeda.previewMode){if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(a=0;a<b.aniData.sL.extra.length;a++)C=b.aniData.sL.extra[a],C.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[a]):b.loadImage("script",b.resDir+b.aniData.sL.extra[a]);b.aniData.sL.cardCommon&&b.loadImage("script","/mugeda_client_utils/js/card_common.js");b.aniData.sL.mugedaPage&&b.loadImage("script","/mugeda_client_utils/js/mugeda_page.js")}else{b.aniData.sL.jquery&&
b.loadImage("script",b.resDir+"jquery-1.10.2.min.js");b.aniData.sL.socketio&&(b.loadImage("script",b.resDir+"socket.io.1.9.16.min.js"),b.loadImage("script",b.resDir+"mugeda_connection.js"));b.aniData.sL.box2d&&b.loadImage("script",b.resDir+"Box2dWeb-2.1.a.3.min.js");b.aniData.sL.qrcode&&(b.loadImage("script",b.resDir+"qrcode.min.js"),b.loadImage("script",b.resDir+"jquery.qrcode.min.js",1));if(b.aniData.sL.extra&&b.aniData.sL.extra.length)for(a=0;a<b.aniData.sL.extra.length;a++){var C=b.aniData.sL.extra[a];
C.indexOf("://")>-1?b.loadImage("script",b.aniData.sL.extra[a]):b.loadImage("script",b.resDir+b.aniData.sL.extra[a])}b.aniData.sL.cardCommon&&b.loadImage("script",b.resDir+"card_common.js");b.aniData.sL.mugedaPage&&b.loadImage("script",b.resDir+"mugeda_page.js")}b.scriptFile&&b.loadImage("script",b.resDir+b.scriptFile,2);setTimeout(function(){b.checkCountDownRef(true,true)},0);var v=function(){if(b.scriptFile){if(b.script=Mugeda.script[Mugeda.script.length-1],typeof b.script=="function")b.script(b),
b.scriptExeced=true}else if(b.aniData.script)(function(a){eval(a.aniData.script)})(b),Mugeda.customScript=b.aniData.script;var a=function(){delete b.evt;b.loadProcess="image";b.afterLoadScriptProcess()},d={stopLoad:false,goOnLoad:function(){d.stopLoad=false}};b.evt=d;o.call(b,"scriptReady",d);d.stopLoad?d.goOnLoad=a:a()};b.checkCountDownRef=function(a,d){function c(){for(var a in b.paramUpdatePool){var d=b.paramUpdatePool[a];d.object.style.cssText+=d.text}b.paramUpdatePool={};a=function(){delete b.evt;
b.loadProcess="loaded";b.loadOver.call(b);b.setupTimer()};var e={stopLoad:false,goOnLoad:function(){e.stopLoad=false}};b.evt=e;o.call(b,"imageReady",e);e.stopLoad?e.goOnLoad=a:a()}a||--b.countDownRef;b.countDownRef==0&&(b.loadProcess=="script"?d?setTimeout(v,10):v():b.loadProcess=="image"&&(d?setTimeout(c,10):c()));this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal);return b.countDownRef};b.afterLoadScriptProcess=function(){if(c.action=="link"&&
c.url&&c.url.length){var a=function(){MugedaMraid.openLink(c.url,c.urlTarget)};this.dom.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false})}c.action=="form"&&c.form&&c.form.length&&(a=function(){MugedaBehavior.popupForm(JSON.parse(c.form))},this.dom.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(b){a();b.preventDefault();b.stopPropagation();return false}));
var d=function(a){var c=c||[];(a=a.layers)&&a.m_operate(function(){var a=this.units;a&&a.m_operate(function(){var a=this.objects;if(a){var e=function(){var a=this.type;a==2005?c.push(b.resDir+this.param.imageSrc):a==2021?c=c.concat(d(b.symbols[this.param.symbolId])):a==2014&&this.items.m_operate(function(){e.call(this)})};a.m_operate(function(){e.call(this)})}})});return c};b.symbols={};b.audioSym={};b.audioSymName={};b.symbolsName={};b.aniData.symbols.m_operate(function(a){if(a.type===2)b.audioSym[a.id]=
b.resDir+a.url,b.audioSymName[a.name]=b.resDir+a.url;else{b.symbols[a.id]=a;b.symbolsName[a.name]=a;var c=99999999,e=-c,h=c,g=-c;a.layers.m_operate(function(a){a.units.m_operate(function(a){a.objects.m_operate(function(a){a=a.param;c=Math.min(c,a.left);e=Math.max(e,a.right);h=Math.min(h,a.top);g=Math.max(g,a.bottom)})})});a.bound={left:c,right:e,top:h,bottom:g,width:e-c,height:g-h};a.zoneCached=false;a.imageList=a.imageList||d(a);var j={guid:Mugeda.guidGen(),type:2021,param:{name:"",fillInfo:{fillStyle:0,
fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:a.bound.width,rawHeight:a.bound.height,symbolId:a.id,offsetX:(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,offsetY:(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2,rotateCenterX:a.bound.width/2,rotateCenterY:a.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-a.bound.width,right:0,top:0,bottom:a.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,
strokeColor:"#0683ff",startX:0,startY:0,endX:a.bound.width,endY:a.bound.height,width:a.bound.width,height:a.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},j=new n(j,null),f={};f.dom=document.createElement("div");f.objectHash={};f.offset={x:a.cw/2+(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,y:a.ch/2+(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2};j.currentScene=f;j.initAndGetDom(f.dom,null);a.cachedInstance=j}});b.scene=new t("_main",c,true,0,{x:0,y:0},g,false,null,
null);b.scene.initAndGetDom();b.updateRuleCached();c.action==="behavior"&&c.behavior&&b.handleBehavior(c.behavior,b.dom,b.id,b.scene);for(var e in b.scene.unitHash)b.scene.unitHash[e]instanceof r&&b.scene.unitHash[e].updateUnitVisibility(false);for(var h in b.imageCache)if(b.imageCache.hasOwnProperty(h)&&!b.imageCache[h].duringBuilding&&(e={noCache:false},o.call(b,"beforeLoadImage",h,b.imageCache[h],e),!e.noCache)){var m=new Image;m.src=h;m.url=h;b.countDownRef++;b.maxNum=b.countDownRef;m.m_event("load",
function(){b.imageCache[this.url].loaded=true;b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;var a=this.url;b.imageCache[this.url].dom.m_operate(function(){this.src=a});b.checkCountDownRef()}).m_event("error",function(){b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();console.log("Error when loading image: "+m.src)})}b.loadImageDecided=true;b.playTriggered=true;B();window.addEventListener("resize",B);b.zoneCachedMode?
b.cacheZone(b.zoneStart,b.zoneEnd,null):b.checkCountDownRef(true)};b.setupTimer=function(){if(!b.timerSetted){var a;if(Mugeda.FPSMeter){var c=document.createElement("div");c.style.cssText+="position: absolute; left: 0; right: 0; background:black; color:red; z-index:999999; width:2em;";a=function(a){c.innerHTML=a.toString()};this.dom.appendChild(c);setInterval(function(){Mugeda.FPSMeter&&a(b.fpsFrame);b.fpsFrame=0},1E3)}b.fpsFrame=0;b.timerSetted=true;b.lastFrameTime=d.getTime();b.nextRenderTime=b.lastFrameTime+
b.frameTime;b.timeDuring=0;b.dom.removeChild(b.loadingDiv);if(Mugeda.enablePulse&&Mugeda.pulse==null){b.insertRule("@"+d.css3Per+"keyframes MugedaPulse","from {"+d.css3Per+"transform: translate(-100px,0px);}to {"+d.css3Per+"transform: translate(-99px,0px);}");b.insertRule(".MugedaStamp","margin-top:-1em;");Mugeda.pulse=d("<div>").m_addClass("MugedaStamp");var e=document.getElementsByTagName("body")[0];e.insertBefore(Mugeda.pulse,e.firstChild);Mugeda.pulse.innerHTML="Mugeda";Mugeda.pulse.style[d.css3PerH+
"Animation"]="MugedaPulse 1s infinite"}(e=b.dom.m_attr("onRenderReady"))&&eval(e);o.call(b,"renderReady");var h=function(){if(!b.stopRedraw){b.fpsFrame++;var a=d.getTime();if(Mugeda.flexibleFrameRate){var c=a-b.lastFrameTime;if(c>b.frameTime)c=b.frameTime;b.timeDuring=c}for(;D(b.scene,true););if(!(c=u.old)){var e;a:{for(e in b.paramUpdatePool){e=false;break a}e=true}c=!e}if(c){Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="running");u.old&&w();for(var j in b.paramUpdatePool)e=
b.paramUpdatePool[j],e.object.style.cssText+=e.text;b.paramUpdatePool={};Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="paused")}j=d.getTime();if(Mugeda.flexibleFrameRate)b.lastFrameTime=a,b.timeoutHandle=setTimeout(h,Math.max(40-(j-a),0));else{b.nextRenderTime+=b.frameTime;if(j>b.nextRenderTime)b.nextRenderTime=j;b.timeoutHandle=setTimeout(h,b.nextRenderTime-j)}}};b.timeoutHandle=setTimeout(h,0)}};typeof MugedaBehavior!="undefined"&&MugedaBehavior.processCloseButton&&MugedaBehavior.processCloseButton();
var D=function(a){if(a!=null){if(a.currentId==null||a.gotoFlag)a.currentId=a.nextId,a.gotoFlag=false;if(a.pauseFlag&&Mugeda.flexibleFrameRate)a.currentId=Math.floor(a.currentId),a.nextId=a.currentId,a.pauseFlag=false;for(var d=a.currentId,c=[],e=Math.floor(d),h=a.cachedAudio?a.cachedAudio[e]||[]:[],j=a.playingAudio||[],g={},f=0;f<h.length;f++){var k=h[f];j[k.hash]&&delete j[k.hash];if(k.audio.playStatus!=1)k.audio.play(),k.audio.playStatus=1;g[k.hash]=k}for(hash in j)if(f=j[hash],f.audio)f=f.audio,
f.pause(),f.playStatus=0,f.currentTime=0,f.playStatus=0;a.playingAudio=g;j=a.cachedVisibility[e]||[];g={};for(f=0;f<j.length;f++)if(j[f].userParam.visible!==false&&(a.lastRenderList[j[f].id]?a.lastRenderList[j[f].id]=false:Mugeda.nonDisplay?j[f].show():j[f].dom.m_css("display",j[f].dom.displayType!=null?j[f].dom.displayType:"block"),g[j[f].id]=j[f]),!u[j[f].id]){if(a.lastDrawId!=d&&j[f].unit&&j[f].unit.data.keyframes.length>1&&j[f].unit.data.objects.length==1){if(a.unitHash[j[f].unit.id].cachedFrame[d])k=
a.unitHash[j[f].unit.id].cachedFrame[d],h=j[f].data.param,h.rawWidth=k.rawWidth,h.rawHeight=k.rawHeight,h.width=k.width,h.height=k.height,h.rotateCenterX=k.rotateCenterX,h.rotateCenterY=k.rotateCenterY,h.left=k.left,h.top=k.top,h.rotate=k.rotate,h.alpha=k.alpha,h.behaviorObj=k.behaviorObj,h.action=k.action;else if((h=TimelineUnit.getKeyframe(j[f].unit.data,d))?Param.exchange(h.param,j[f].data.param,true):(h=TimelineUnit.getTweenParam(j[f].unit.data,d))&&Param.exchange(h,j[f].data.param,true),!Mugeda.flexibleFrameRate)k=
j[f].data.param,a.unitHash[j[f].unit.id].cachedFrame[d]={rawWidth:k.rawWidth,rawHeight:k.rawHeight,width:k.width,height:k.height,rotateCenterX:k.rotateCenterX,rotateCenterY:k.rotateCenterY,left:k.left,top:k.top,rotate:k.rotate,alpha:k.alpha,behaviorObj:k.behaviorObj,action:k.action};c.push(j[f])}if(j[f].symbolList)for(h=0;h<j[f].symbolList.length;h++)if(k=D(b.sceneHash[j[f].symbolList[h]]),typeof k=="string")return k;else c=c.concat(k);a.lastDrawId!=d&&(h=j[f].data.param.behaviorObj||j[f].data.param.behavior,
j[f].data.param.action=="behavior"&&h&&b.handleBehavior(h,j[f].dom,j[f].id,a,j[f].unit))}for(var m in a.lastRenderList)a.lastRenderList[m]&&(Mugeda.nonDisplay?a.lastRenderList[m].hide():a.lastRenderList[m].dom.m_css("display","none"));a.lastRenderList=g;if(a.playing&&!a.gotoFlag)Mugeda.flexibleFrameRate?a.nextId=a.currentId+b.timeDuring/b.frameTime:a.nextId++;for(o.call(a,"enterframe");a.frameout.length&&a.frameout[0].time==0;)m=a.frameout[0].fun,a.frameout.splice(0,1),m.call(a);a.frameout.length&&
a.frameout[0].time--;if(a.currentSegment&&a.currentSegment.from!=void 0)m=a.currentSegment,a.nextId>m.to&&(m.isLoop?a.gotoAndPlay(a.currentSegment.from):(a.gotoAndPause(m.to),a.lastDrawId!=d&&o.call(a,"segmentend")));else if(a.nextId>=a.length)a.id=="_main"&&!b.aniData.loop?a.nextId=a.length-1:a.looped==false?a.nextId=a.length-1:(a.nextId=0,showAnimation=false);a.currentId=a.nextId;a.lastDrawId=d;if(a.pauseFlag&&Mugeda.flexibleFrameRate&&d!=e)return"inval";if(a.id!="_main")return c;else{for(f=0;f<
c.length;f++)c[f].updateObjectParam();return null}}};e.prototype.createInstanceOfSymbol=function(a,d){var c=b.symbolsName[a],e=b.audioSymName[a];if(c)return c={guid:Mugeda.guidGen(),type:2021,param:{name:d,fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:c.bound.width,rawHeight:c.bound.height,symbolId:c.id,offsetX:(c.bound.left+c.bound.right-c.cw-c.bound.width)/2,offsetY:(c.bound.top+c.bound.bottom-c.ch-c.bound.height)/
2,rotateCenterX:c.bound.width/2,rotateCenterY:c.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-c.bound.width,right:0,top:0,bottom:c.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:c.bound.width,endY:c.bound.height,width:c.bound.width,height:c.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},new n(c,null);else if(e)return m(e)};e.prototype.unloadAnimation=function(){this.stopRedraw=true;
this.dom&&this.dom.parentNode.removeChild(this.dom)}}};e.prototype.checkLoad=function(a){a&&--this.imageNum;this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.imageNum)/this.zoneLoadTotal);this.imageNum==0&&(this.loadOver.call(this),this.setupTimer())};e.prototype.loadAudio=function(a){e.prototype.loadImage("audio",a)};e.prototype.loadImage=function(a,c,d){d==null&&(d=0);var b=this;b.countDownRef=b.countDownRef||0;if(a=="dom_back"){var d=c.dom,e=c.url,a=c.duringBuilding&&c.unit||
false,f=c.cacheZone||false;if(b.imageCache[e])if(b.imageCache[e].loaded){if(d)d.src=e;return false}else if(f){if(b.imageCache[e].loading)return false;g=new Image;g.src=e;g.url=e;b.imageCache[e].loaded=true;b.countDownRef++;b.maxNum=b.countDownRef;g.m_event("load",function(){b.checkCountDownRef();b.imageCache[this.url].dom.m_operate(function(){this.src=e})}).m_event("error",function(){console.log("Error when loading image: "+g.src);b.checkCountDownRef()});return b.imageCache[e].loading=true}else return b.imageCache[e].dom.push(d),
a&&c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false;else if(a)return b.imageCache[e]={image:null,url:e,dom:[d],loaded:false,duringBuilding:true},c.scene&&c.scene.id=="_main"&&c.unit&&(c.unit.imageList[e]=b.imageCache[e]),false;else if(b.imageCache[e]={image:g,dom:[d],loaded:false},b.loadImageDecided){var g=new Image;g.src=e;g.url=e;g.m_event("load",function(){b.imageCache[this.url].loaded=true;b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;
var a=this.url;b.imageCache[this.url].dom.m_operate(function(){this.src=a})}).m_event("error",function(){console.log("Error when loading image: "+g.src)})}}else if(a=="script"){b.countDownRef++;b.maxNum=b.countDownRef;for(a=b.scriptList.length;a<d;a++)b.scriptList[a]=[];b.scriptList[d]=b.scriptList[d]||[];b.scriptList[d].push(c);if(typeof l!="undefined")return Mugeda.loadJs(c);var l=-1;if(!b.scriptLoadTimer)b.scriptLoadTimer=setTimeout(function(){var a=function(c){if(!(c>=b.scriptList.length)){var d=
b.scriptList[c];d||a(++c);for(var e=d.length,h=0;h<d.length;h++)Mugeda.loadJs(d[h],function(){b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();--e==0&&a(++c)},function(){console.log("Error when loading user script");b.loadingDiv.innerHTML="Loading..."+(b.maxNum-b.countDownRef+1)+"/"+b.maxNum;b.checkCountDownRef();--e==0&&a(++c)});d.length==0&&a(++c)}};a(++l)},0)}else a="audio"};e.prototype.cacheZone=function(a,c,d,b){if(c==null||c<a)c=a;a<0&&(a=0);
var e=this;if(e.scene){a++;c++;if(c>e.scene.length)c=e.scene.length;d==null&&(d=[]);e.zoneCachedMode=true;e.zoneLoadCallback=b||function(){};var f={},g={},l=0;for(a-=1;a<c;a++)e.zoneCached[a]||(e.mainSceneFrameUnitHash[a].m_operate(function(){if(!this.zoneCached){this.symbolList.m_operate(function(){e.symbols[this.toString()]&&(f[this.toString()]=e.symbols[this.toString()])});d.m_operate(function(){var a=this.toString();f[e.symbolsName[a].id]=e.symbolsName[a]});var a=this.imageList;for(c in a)a[c].loaded==
false&&(g[c]=a[c]);for(var b in f)if(a=f[b],a.zoneCached==false)a.imageList.m_operate(function(){var a=this.toString();g[a]||(g[a]={dom:[],url:a})}),a.zoneCached=true;for(var c in g)g[c].url&&e.loadImage("dom_back",{url:c,cacheZone:true,dom:[]})&&l++;this.zoneCached=true}}),e.zoneCached[a]=true);e.zoneLoadTotal=l;l==0&&(c=(this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal,e.zoneLoadCallback(c?c:1))}else e.zoneCachedMode=true,e.zoneStart=a,e.zoneEnd=c};var r=function(a){var c=a.className,d=
c.indexOf("guid");return d>-1?(a=c.indexOf(" ",d),a==-1?c.substr(d):c.substr(d,a-d)):(c="guid_"+Mugeda.guidGen(),a.m_addClass(c),c)};e.prototype.insertRuleCached=function(a,c){if(this.cachedRule){if(this.cachedRule.push({obj:a,cssText:c}),!this.waitToupdateRuleCached){this.waitToupdateRuleCached=true;var d=this;setTimeout(function(){d.updateRuleCached()},0)}}else this.insertRule("."+r(a),c)};e.prototype.updateRuleCached=function(){for(var a=0;a<this.cachedRule.length;a++){var c=this.cachedRule[a];
this.insertRule("."+r(c.obj),c.cssText)}this.cachedRule=[];delete this.waitToupdateRuleCached};e.prototype.insertRule=function(a,c){var d=this.externalStylesheet,b=this.indexedStylesheet;if(b[a]&&b[a].style)b[a].style.cssText+=c;else{var e=0,f=d.rules?d.rules.length:d.cssRules.length;d.insertRule?e=d.insertRule(a+"{"+c+"}",f):d.addRule&&(e=d.addRule(a,c,f));b[a]=d.rules?d.rules[e]:d.cssRules[e]}};e.prototype.handleBehavior=function(a,c,d,b,e){var g=this;(typeof a=="string"?JSON.parse(a):a).m_operate(function(a,
h){var l=null;a.unit=e?e.data||{}:{};a.param=a.param||{};var n=a.param.scope=="symbol"?b:g.scene;if(a.type=="play")l=function(){n.play.call(n)};else if(a.type=="pause")l=function(){n.pause.call(n)};else if(a.type=="gotoAndPlay"){var o=a.param.frame_number,o=parseInt(o);if(isNaN(o))o=a.param.frame_name;l=function(){n.gotoAndPlay.call(n,o,true)}}else if(a.type=="gotoAndStop"||a.type=="gotoAndPause"){o=a.param.frame_number;o=parseInt(o);if(isNaN(o))o=a.param.frame_name;l=function(){n.gotoAndPause.call(n,
o,true)}}else if(a.type=="next")parseInt(a.param.frame_number),l=function(){n.gotoAndPause.call(n,Math.min(n.length,n.currentId+0+1))};else if(a.type=="previous")parseInt(a.param.frame_number),l=function(){n.gotoAndPause.call(n,Math.max(1,n.currentId-2+1))};else if(a.type!="callback")if(a.type=="audio"){if(a.param.audio_id)a.param.audio_url=g.audioSym[a.param.audio_id]}else a.type=="stopAllAudio"&&(l=function(){for(var a in g.audioList){var b=g.audioList[a];try{b.pause(),b.currentTime=0}catch(c){}}});
if(a.event=="click"){if(!n.clickEventAttached[d+"_"+h])c.style.cursor="pointer",c.m_event(f?"touchend":"mouseup",function(b){MugedaBehavior.processAction(a,"click",true);l&&l.call();b.preventDefault();b.stopPropagation();return false}),n.clickEventAttached[d+"_"+h]=true}else a.event=="appear"&&(l?l():MugedaBehavior.processAction(a,"appear",true))})};window.HTMLElement.prototype.m_attr=function(a,c){return typeof c!="undefined"?(this.setAttribute(a,c),this):this.getAttribute(a)};window.HTMLElement.prototype.m_addClass=
function(a){if(a&&typeof a==="string")this.className=this.className?this.className+" "+a:a;return this};window.HTMLElement.prototype.m_removeClass=function(a){if(a&&typeof a==="string"&&this.className)this.className=this.className.replace(RegExp("("+a+"\\s)|(\\s*"+a+")"),"");return this};window.HTMLElement.prototype.m_event=function(a,c,e){/(transition)|(other)/.test(a)&&(a=d.css3Per+(d.css3Per?a.substr(0,1).toUpperCase():a.substr(0,1))+a.substr(1));this.addEventListener(a,c,e||false);return this};
var w={transform:d.css3Per+"transform",transition:d.css3Per+"transition",textStroke:d.css3Per+"textStroke",textFillColor:d.css3Per+"textFillColor","transform-origin":d.css3Per+"transform-origin"};window.HTMLElement.prototype.m_css=function(a,c,e){w[a]&&(a=w[a]);if(c!=null)if(e)if(c!==""){if(this.guid==null)this.guid=Mugeda.guidGen();e.paramUpdatePool[this.guid]==null&&(e.paramUpdatePool[this.guid]={object:this,text:""});e.paramUpdatePool[this.guid].text+=a+":"+c+";"}else this.style[a]=null;else a.indexOf("opacity")>
-1||a.indexOf("tran")>-1||!Mugeda.nonDisplay&&a.indexOf("display")>-1||!Mugeda.nonDisplay&&a.indexOf("vertical")>-1?c!==""?this.style.cssText+=a+":"+c+";":this.style[a]=null:c!==""?Mugeda.currentAni.insertRuleCached(this,a+":"+c+";"):this.style[a]=null;else return d.getCurrentStyle(this,a);return this};window.HTMLElement.prototype.m_width=function(a){if(a!=void 0)return this.m_css("width",a+"px")};window.HTMLElement.prototype.m_height=function(a){if(a!=void 0)return this.m_css("height",a+"px")};window.HTMLElement.prototype.m_transform=
function(a,c,d,b,e,f,g){data={};a!=null&&(data.translateX=a.toString()+"px");c!=null&&(data.translateY=c.toString()+"px");d!=null&&(data.rotate=d.toString()+"rad");b!=null&&(data.scaleX=b.toString());b!=null&&(data.scaleY=e.toString());Mugeda.threeDRendering&&(data.translateZ="0px");var a="",l;for(l in data)a+=l+"("+data[l]+") ";if(f!=null||g!=null)this.m_css("transform-origin",(Math.abs(f)<0.01?0:Math.floor(100*f)*0.01)+"px "+(Math.abs(g)<0.01?0:Math.floor(100*g)*0.01)+"px");return this.m_css("transform",
a)};window.HTMLElement.prototype.m_append=function(a,c){a instanceof window.HTMLElement&&(c?this.insertBefore(a,c):this.appendChild(a));return this};window.HTMLElement.prototype.m_appendTo=function(a){a instanceof window.HTMLElement&&a.appendChild(this);return this};window.HTMLElement.prototype.m_setCapture=function(a){MugedaCss3.captureObject={object:this,capture:a==void 0?true:a};return this};window.HTMLElement.prototype.m_releasecapture=function(){MugedaCss3.captureObject=null;return this};Array.prototype.m_operate=
function(a,c){for(var d=c?this.length-1:0;c&&d>=0||!c&&d<this.length;c?d--:d++)if(a.call(this[d],this[d],d)==false)break};String.prototype.m_trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};return d}}(window.MugedaCss3);
var MugedaCompress={keys:"Ac,action,fM,form,tt,title,wt,width,ht,height,cl,color,sm,symbols,ly,layers,vr,version,sC,scripts,zI,zoomInfo,pd,pid,tp,type,nm,name,un,units,lI,layerId,fS,frameStart,fC,frameCount,ad,animated,vb,visible,ob,objects,pm,param,fI,fillInfo,cv,curve,kf,keyframes,md,mode,tw,tween,hK,hashKey,ix,index,rW,rawWidth,rH,rawHeight,sI,symbolId,oX,offsetX,oY,offsetY,rX,rotateCenterX,rY,rotateCenterY,it,items,nI,nodeId,gP,guidPath,ph,path,gi,guid,sm,smooth,iX,innerX,iY,innerY,uX,outerX,uY,outerY,cX,centerX,cY,centerY,ed,edges,st,section,fZ,fontSize,fT,fontStyle,fW,fontWeight,fF,fontFamily,tA,textAlign,tC,textContent,tD,textDecoration,cR,cornerRadius,iS,imageSrc,lC,lineCap,lJ,LineJoin,fR,frameRate,iP,innerPercent,TA,trackAnchors,MT,mugedaTrackAnchors".split(","),unzip:function(a){if(!a)return a;
if(a.zip!=1)return HaniData.unzip(a);a=JSON.parse(JSON.stringify(a));a=MugedaCompress.unzipKey(a);delete a.zip;if(a.rate==void 0)a.rate=12;if(a.width==void 0)a.width=600;if(a.height==void 0)a.height=400;if(a.guid==void 0)a.guid="";if(a.title==void 0)a.title="";if(a.script==void 0)a.script="";if(a.loop==void 0)a.loop=true;if(a.useCamera==void 0)a.useCamera=false;if(a.symbols==void 0)a.symbols=[];if(a.symbols.length)for(var d=a.symbols,c=0;c<d.length;c++){var e=d[c];e.runtime=true;e.dirtyFlag=false;
MugedaCompress.unzipLayers(e.layers)}MugedaCompress.unzipZoomInfo(a);MugedaCompress.unzipLayers(a.layers);return a},unzipKey:function(a){for(var d,a=JSON.stringify(a),c=0;c<MugedaCompress.keys.length;c+=2)d=eval('/"'+MugedaCompress.keys[c]+'":/g'),a=a.replace(d,'"'+MugedaCompress.keys[c+1]+'":');return JSON.parse(a)},unzipZoomInfo:function(a){for(var d=[],c=a.zoomInfo.split(",")||[],e=0;e<c.length;e+=4){var g=c[e];if(g.indexOf("i")==0){g=g.substr(1);e++;var f=c[e];f.indexOf("t")==0?(f=f.substr(1),
e++):f=null;d[g]={offsetLeft:Number(c[e]),offsetTop:Number(c[e+1]),rotation:Number(c[e+2]),zoomLevel:Number(c[e+3])};if(f)d[g].tween=f}}a.zoomInfo=d},unzipLayers:function(a){for(var d=0;d<a.length;d++){var c=a[d];c.hide=false;c.lock=false;for(var c=c.units,e=0;e<c.length;e++){var g=c[e];g.animated&&MugedaCompress.unzipPath(g);for(var f=g.keyframes||[],l=0;l<f.length;l++)MugedaCompress.unzipParam(f[l].param);if(g.visible==void 0)g.visible=true;MugedaCompress.unzipObjects(g.objects)}}},unzipPath:function(a){for(var d=
a.path.split(","),c=[],e=d.shift(),g=d.shift(),f=0;f<d.length;f+=7)c.push({id:Number(d[f]),backwardX:Number(d[f+1]),backwardY:Number(d[f+2]),forwardX:Number(d[f+3]),forwardY:Number(d[f+4]),nodeX:Number(d[f+5]),nodeY:Number(d[f+6])});c.length?(a.pathLeft=Number(e),a.pathTop=Number(g),a.path=c):(delete a.path,delete a.pathLeft,delete a.pathTop)},unzipObjects:function(a){for(var d=0;d<a.length;d++){var c=a[d];c.items&&c.items.length?MugedaCompress.unzipObjects(c.items):(c.id=0,c.name="",c.items=[],c.aryAnchors=
[]);MugedaCompress.unzipCurve(c);MugedaCompress.unzipParam(c.param)}},unzipCurve:function(a){var d=a.curve;if(typeof d=="string"){a.curve={};var d=d.split(","),c=d.shift()==1;a.curve.closed=c;for(var c=[],e=0;e<d.length;e+=6)c.push({backwardX:Number(d[e]),backwardY:Number(d[e+1]),forwardX:Number(d[e+2]),forwardY:Number(d[e+3]),nodeX:Number(d[e+4]),nodeY:Number(d[e+5])});a.curve.points=c}},unzipParam:function(a){if(a.strokeType==void 0)a.strokeType=0;if(a.frameRate==void 0)a.frameRate=12;if(a.lineCap==
void 0)a.lineCap="round";if(a.lineJoin==void 0)a.lineJoin="round";for(var d=a.m.split(";"),c=0;c<d.length;c++){var e=d[c].substr(0,1),g=d[c].substr(1);switch(e){case "L":a.left=Number(g);break;case "R":a.right=Number(g);break;case "T":a.top=Number(g);break;case "B":a.bottom=Number(g);break;case "S":a.startX=Number(g);break;case "P":a.startY=Number(g);break;case "E":a.endX=Number(g);break;case "N":a.endY=Number(g);break;case "X":a.scaleX=Number(g);break;case "Y":a.scaleY=Number(g);break;case "O":a.rotate=
Number(g);break;case "W":a.lineWidth=Number(g);break;case "A":a.alpha=Number(g);break;case "C":a.strokeColor=g}}if(a.startX==void 0)a.startX=a.left;if(a.startY==void 0)a.startY=a.top;if(a.endX==void 0)a.endX=a.right;if(a.endY==void 0)a.endY=a.bottom;a.width=a.right-a.left;a.height=a.bottom-a.top;delete a.m;MugedaCompress.unzipFillInfo(a)},unzipFillInfo:function(a){if(a.fillInfo){for(var d=a.fillInfo.split(";"),c=Number(d[0]),e=d[1].split(","),g=d[3],f=[],l=0;l<e.length;l+=5)f.push({p:Number(e[l]),
r:Number(e[l+1]),g:Number(e[l+2]),b:Number(e[l+3]),a:Number(e[l+4])});c={fillStyle:c,fillImage:g,fillColors:f};d=d[2].split(",");d.length!=4&&(d=[0,0,0,0]);c.fillStartPos={x:Number(d[0]),y:Number(d[1])};c.fillEndPos={x:Number(d[2]),y:Number(d[3])};a.fillInfo=c}}},TimelineUnit={getKeyframe:function(a,d){var c=a.hashKey["key_"+d];c||(c=null);return c},getTweenParam:function(a,d){var c=a.keyframes.length,e=a.keyframes[0],g=null,f=null,l=0,x=-1;bezierInterpolate=function(a,c,b,d,e,f){return Math.pow(c,
3)*b+3*Math.pow(c,2)*a*d+3*c*Math.pow(a,2)*e+Math.pow(a,3)*f};var o=function(a,c,b){var d=1-b,e=a.nodeY,f=a.forwardY,h=c.backwardY,g=c.nodeY,a=bezierInterpolate(b,d,a.nodeX,a.forwardX,c.backwardX,c.nodeX),b=bezierInterpolate(b,d,e,f,h,g);return{x:a,y:b}};if(c>1&&!a.hashKey["key_"+d]){for(var r=1;r<c;r++){g=a.keyframes[r];if(g.id>d){x=r;break}e=g;l=r;g=null}if(g){c=Math.abs(g.id-e.id);f=d-e.id;c=TimelineUnit.getTweenFactors(c,e.tween);if(Mugeda.flexibleFrameRate){c.push(1);var r=Math.floor(f),w=Math.ceil(f),
h=c[r],c=c[w],c=w==r?c:(f-w)*(c-h)/(w-r)+c}else c=c[f];f={left:0,top:0,right:0,bottom:0,startX:0,startY:0,endX:0,endY:0,width:0,height:0,alpha:1,rotate:0,scaleX:1,scaleY:1,lineWidth:1,strokeType:0,strokeColor:"#0683ff",lineCap:"round",lineJoin:"round",fillInfo:{fillStyle:0,fillImage:"",fillStartPos:{x:32,y:10},fillEndPos:{x:80,y:100},fillColors:[{p:0,r:144,g:200,b:255,a:1},{p:0.8,r:255,g:144,b:200,a:1},{p:1,r:200,g:255,b:144,a:1}]}};Param.tweenParam(f,e.param,g.param,c);if(a.pathMode>Hanimation.PATHMODE_DEFAULT&&
l>=0&&x>=0)g=a.path,l=o(g[l],g[x],c),l.x=a.pathLeft+l.x-f.rotateCenterX,l.y=a.pathTop+l.y-f.rotateCenterY,f.startX=l.x,f.startY=l.y,f.endX=f.startX+f.width,f.endY=f.startY+f.height,f.left=f.startX,f.top=f.startY,f.right=f.endX,f.bottom=f.endY}}if(!f)f=e.param;return f},getTweenFactors:function(a,d){var c=[],e=new TWEEN.Tween({x:0});e.to({x:1},1E3);d||(d="Linear.EaseNone");for(var d=d.split("."),g=d.length,f=TWEEN.Easing;g;)f=f[d[d.length-g]],g--;e.easing(f);for(g=0;g<a;g++)c[g]=e.getFactor(g/a);return c}},
TWEEN=TWEEN||function(){var a,d,c,e,g=[];return{start:function(a){c=setInterval(this.update,1E3/(a||60))},stop:function(){clearInterval(c)},add:function(a){g.push(a)},getAll:function(){return g},removeAll:function(){g=[]},remove:function(c){a=g.indexOf(c);a!==-1&&g.splice(a,1)},update:function(){a=0;d=g.length;for(e=(new Date).getTime();a<d;)g[a].update(e)?a++:(g.splice(a,1),d--)}}}();
TWEEN.Tween=function(a){var d={},c={},e={},g=1E3,f=0,l=null,x=TWEEN.Easing.Linear.EaseNone,o=null,r=null,w=null;this.to=function(c,d){d!==null&&(g=d);for(var f in c)a[f]!==null&&(e[f]=c[f]);return this};this.start=function(){TWEEN.add(this);l=(new Date).getTime()+f;for(var h in e)a[h]!==null&&(d[h]=a[h],c[h]=e[h]-a[h]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){x=a;return this};this.chain=function(a){o=a};this.onUpdate=
function(a){r=a;return this};this.onComplete=function(a){w=a;return this};this.getFactor=function(a){a=Math.min(1,Math.max(0,a));return x(a)};this.update=function(e){var f,k;if(e<l)return true;e=(e-l)/g;e=e>1?1:e;k=x(e);for(f in c)a[f]=d[f]+c[f]*k;r!==null&&r.call(a,k);return e==1?(w!==null&&w.call(a),o!==null&&o.start(),false):true}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{},Step:{}};
TWEEN.Easing.Linear.EaseNone=function(a){return a};TWEEN.Easing.Quadratic.EaseIn=function(a){return a*a};TWEEN.Easing.Quadratic.EaseOut=function(a){return-a*(a-2)};TWEEN.Easing.Quadratic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)};TWEEN.Easing.Cubic.EaseIn=function(a){return a*a*a};TWEEN.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};TWEEN.Easing.Cubic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)};TWEEN.Easing.Quartic.EaseIn=function(a){return a*a*a*a};
TWEEN.Easing.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};TWEEN.Easing.Quartic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};TWEEN.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};TWEEN.Easing.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};TWEEN.Easing.Quintic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};TWEEN.Easing.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};
TWEEN.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};TWEEN.Easing.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};TWEEN.Easing.Exponential.EaseIn=function(a){return a==0?0:Math.pow(2,10*(a-1))};TWEEN.Easing.Exponential.EaseOut=function(a){return a==1?1:-Math.pow(2,-10*a)+1};TWEEN.Easing.Exponential.EaseInOut=function(a){return a==0?0:a==1?1:(a*=2)<1?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};
TWEEN.Easing.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};TWEEN.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};TWEEN.Easing.Circular.EaseInOut=function(a){return(a/=0.5)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};TWEEN.Easing.Elastic.EaseIn=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return-(c*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/e))};
TWEEN.Easing.Elastic.EaseOut=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return c*Math.pow(2,-10*a)*Math.sin((a-d)*2*Math.PI/e)+1};
TWEEN.Easing.Elastic.EaseInOut=function(a){var d,c=0.1,e=0.25;if(a==0)return 0;if(a==1)return 1;e||(e=0.3);!c||c<1?(c=1,d=e/4):d=e/(2*Math.PI)*Math.asin(1/c);return(a*=2)<1?-0.5*c*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/e):c*Math.pow(2,-10*(a-=1))*Math.sin((a-d)*2*Math.PI/e)*0.5+1};TWEEN.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};TWEEN.Easing.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};
TWEEN.Easing.Back.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};TWEEN.Easing.Bounce.EaseIn=function(a){return 1-TWEEN.Easing.Bounce.EaseOut(1-a)};TWEEN.Easing.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};
TWEEN.Easing.Bounce.EaseInOut=function(a){return a<0.5?TWEEN.Easing.Bounce.EaseIn(a*2)*0.5:TWEEN.Easing.Bounce.EaseOut(a*2-1)*0.5+0.5};TWEEN.Easing.Step.EaseIn=function(){return 0};
Param={exchange:function(a,d,c){c?(c=a,a=d):c=d;a.startX=c.startX;a.startY=c.startY;a.endX=c.endX;a.endY=c.endY;a.left=c.left;a.right=c.right;a.top=c.top;a.bottom=c.bottom;a.width=c.width;a.height=c.height;a.alpha=c.alpha;a.scaleX=c.scaleX;a.scaleY=c.scaleY;a.rotate=c.rotate;a.rotateCenterX=c.rotateCenterX;a.rotateCenterY=c.rotateCenterY;a.customPivot=c.customPivot},tweenParam:function(a,d,c,e){a.startX=d.startX+e*(c.startX-d.startX);a.startY=d.startY+e*(c.startY-d.startY);a.endX=d.endX+e*(c.endX-
d.endX);a.endY=d.endY+e*(c.endY-d.endY);a.width=d.width+e*(c.width-d.width);a.height=d.height+e*(c.height-d.height);a.alpha=d.alpha+e*(c.alpha-d.alpha);a.scaleX=d.scaleX+e*(c.scaleX-d.scaleX);a.scaleY=d.scaleY+e*(c.scaleY-d.scaleY);a.rotate=d.rotate+e*(c.rotate-d.rotate);a.rotateCenterX=d.rotateCenterX+e*(c.rotateCenterX-d.rotateCenterX);a.rotateCenterY=d.rotateCenterY+e*(c.rotateCenterY-d.rotateCenterY);a.customPivot=true;if(d.fillInfo&&d.fillInfo&&(d.fillInfo.fillStyle==1||d.fillInfo.fillStyle==
2))a.fillInfo.fillStartPos.x=d.fillInfo.fillStartPos.x+e*(c.fillInfo.fillStartPos.x-d.fillInfo.fillStartPos.x),a.fillInfo.fillStartPos.y=d.fillInfo.fillStartPos.y+e*(c.fillInfo.fillStartPos.y-d.fillInfo.fillStartPos.y),a.fillInfo.fillEndPos.x=d.fillInfo.fillEndPos.x+e*(c.fillInfo.fillEndPos.x-d.fillInfo.fillEndPos.x),a.fillInfo.fillEndPos.y=d.fillInfo.fillEndPos.y+e*(c.fillInfo.fillEndPos.y-d.fillInfo.fillEndPos.y);a.left=a.startX;a.top=a.startY;a.right=a.startX+a.width;a.bottom=a.startY+a.height}};
Hanimation={PATHMODE_DEFAULT:0};
(function(){Mugeda.initCss3Player=function(){document.addEventListener("mousedown",MugedaCss3.handleCapture,true);document.addEventListener("mouseup",MugedaCss3.handleCapture,true);document.addEventListener("mouseover",MugedaCss3.handleCapture,true);document.addEventListener("mouseout",MugedaCss3.handleCapture,true);document.addEventListener("mousemove",MugedaCss3.handleCapture,true);Mugeda.loadJs=function(c,d,e){if(a(c))d&&d();else{var f=document.createElement("script");f.src=c;document.getElementsByTagName("head")[0].appendChild(f);
f.onload=f.onreadystatechange=function(){!(this.readyState&&this.readyState=="loading")&&d&&(d(),d=function(){})};f.onerror=function(){f.parentNode.removeChild(f);e()}}};var a=function(a){var c=document.getElementsByTagName("script"),d=false;for(e=0;e<c.length;e++)if(c[e].src&&c[e].src.indexOf(a)!=-1&&(c[e].readyState=="loaded"||c[e].readyState=="complete")){d=true;break}return d};Mugeda.startAnimation=function(a,c,d,e,f){var g=navigator.userAgent.toLowerCase();Mugeda.isAndroid=g.indexOf("android")>
-1;Mugeda.androidVersion=parseFloat(g.slice(g.indexOf("android")+8));var k=MugedaCss3.initAnimation(Mugeda.data[a],c,d,e,function(){f&&(MugedaCss3.stage[f]=k)});Mugeda.scene=k;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)};if(Mugeda.css3PlayerLoaded==void 0)for(var d=document.getElementsByClassName("MugedaStage"),c=d.length,e=0;e<c;e++){var g=d[e],f=g.getAttribute("mugedaName"),l=MugedaCss3.initAnimation(Mugeda.data[f],g.m_attr("hasScript")=="true"?"actions_"+(f.substr(f.indexOf("_")+
1)+".js"):"",g,g.m_attr("relDir")||"",function(){MugedaCss3.stage[f]=l;--c==0&&typeof Mugeda.script=="function"&&Mugeda.script()});Mugeda.scene=l;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)}else if(Mugeda.css3PlayerLoaded=2,Mugeda.creationToBeLoad){for(e=0;e<Mugeda.creationToBeLoad.length;e++)Mugeda.creationToBeLoad[e].start();Mugeda.creationToBeLoad=[]}}})();
document&&document.getElementsByTagName&&document.getElementById&&document.body?Mugeda.initCss3Player():document.addEventListener("DOMContentLoaded",Mugeda.initCss3Player);
